### ISSUE TITLE
Access edges & faces info more conveniently.

### ISSUE THREAD

**Issue by Xayahp** [pmp-library/pmp-library#104]
**Is your feature request related to a problem? Please describe.**

When integrate pmp with [libigl](https://github.com/libigl/libigl), an Eigen based Geometry processing library, I found it so hard for me to achieve a fast and elegant way to translate all faces data & edges data into an Eigen::MatrixXd. I noticed some helper class like `EdgeContainer` and `EdgeIterator` etc., but I'm still get frustrated and found myself really hard to use them properly. I try to read the source code and official docs thoroughly, but I stiil can't manage it.

For faces translation, I write code like this~
```
    TriFaceMatrix F;
    F.resize(static_cast<Eigen::Index>(mesh.n_faces()), 3);
    {
        int it = 0;
        for (auto &&f: mesh.faces())
        {
            SurfaceMesh::VertexAroundFaceCirculator vs = mesh.vertices(f);
            Vector3i _f;
            int _it = 0;
            for (auto &&v: vs)
            {
                assert(_it < 3); // ensure triangulated
                _f[_it++] = static_cast<Eigen::DenseCoeffsBase<Eigen::Matrix<int, 3, 1, 0>, 1>::Scalar>(v.idx());
            }
            F.row(it) = _f.transpose();
            ++it;
        }
    }
```
but, how can I translate all edges( not half edges), as well as more other infos, into Eigen::MatrixXd, with an more elegant way? I think there should have been a more convenient way to access some common properties like `faces` and `edges`, but unfortunately, there seems not have been.

**Describe the solution you'd like**
I think maybe there should have more helper functions to facilitate direct common property access, with usage probably like below~
```
for (SurfaceMesh::NewEdgeType &&e: mesh.edges())
{
    int first_vertex = e.vertex_id1();
    int second_vertex = e.vertex_id2();
    ...
}
for (SurfaceMesh::NewFaceType &&f: mesh.face())
{
    int first_vertex = f.vertex_id1();
    int second_vertex = f.vertex_id2();
    int third_vertex = f.vertex_id3();
    int first_edge = f.edge_id1();
    int second_edge = f.edge_id2();
    int third_edge = f.vertex_id3();
    ...
}
...
```

**Comment by dsieger** [comment]
From what I understand accessing all information you need should be possible with our iterators and circulators and the corresponding query functions of the SurfaceMesh class. I won't add convenience functions with hard-coded indices which are redundant with the existing API.
