### ISSUE TITLE
How to obatain the edge neighbor index.

### ISSUE THREAD

**Issue by ztdepztdep** [pmp-library/pmp-library#105]
I want to obtain the edge neighbors informations. which api to use?

**Comment by dsieger** [comment]
What do you mean exactly by edge neighbors? Given an edge, what are you looking for? Adjacent vertices, faces, edges?

**Comment by ztdepztdep** [comment]
I want working with 2d Mesh, then i want to find the neighboring face of the edge in the 2d.

**Comment by dsieger** [comment]
That's easily done with standard connectivity queries:

```c++
Edge e;
Face f0 = mesh.face(e, 0);
Face f1 = mesh.face(e, 1);
```

Please be sure to checkout the [tutorial](http://www.pmp-library.org/tutorial.html) and the [reference documentation](http://www.pmp-library.org/classpmp_1_1_surface_mesh.html).

**Comment by ztdepztdep** [comment]
thanks you very much for your help. 
Does pmp support naming some boundary edges or faces of the mesh so i can find it during the numerical computation by its name.
