### ISSUE TITLE
 Does pmp support naming some boundary edges or faces of the mesh..

### ISSUE THREAD

**Issue by ztdepztdep** [pmp-library/pmp-library#107]
I need to define the boundary name so i can find its corresponding edges or faces. 
Does pmp support naming some boundary edges or faces of  the mesh.

**Comment by dsieger** [comment]
Yes, you can attach arbitrary properties to mesh entities, so you could either tag boundary edges by an ID or a name. See the section "Dynamic Properties" of the [tutorial](http://www.pmp-library.org/tutorial.html).
