### ISSUE TITLE
An infinite loop appears in the faces traversed through the model

### ISSUE THREAD

**Issue by breakerrorchen** [pmp-library/pmp-library#110]
When I load the model using PMP，and traverse faces appears infinite loop 

```cpp
pmp::SurfaceMesh mesh_;
mesh_.read("a.obj");
for (auto fd : mesh_.faces()) {
// hear infinite loop
}
```
[a.obj.zip](https://github.com/pmp-library/pmp-library/files/8885374/a.obj.zip)

**Comment by dsieger** [comment]
I can't reproduce the issue. Loading the model and iterating over faces works fine for me. I also don't see anything obvious being wrong with the mesh.

Which version of PMP are you using?  Latest release? Current master?

**Comment by dsieger** [comment]
Closing due to lack of feedback and reproducibility.
