### ISSUE TITLE
Triangulate polygon seperately

### ISSUE THREAD

**Issue by waverider404** [pmp-library/pmp-library#112]
Hello : )

I am trying to triangulate my polygon like this, but i want to keep the triangles seperate from the original face, but it's not efficient, there's some memory leak. Is  there a better method to triangulate my mesh but keep the triangles generated seperate from the original face. i need the triangles for rendering only

`      

       tempM.clear();
        tempM.free_memory();

        tempM.assign(mesh);

        SurfaceTriangulation tesselator(mesh);
        tesselator.triangulate();
        
        retrieveTriangles();
        mesh.assign(tempM);
  
`

**Comment by dsieger** [comment]
Just making a shallow copy of the original mesh and triangulating it should be fine:

```c++
auto polymesh = SurfaceFactory::hexahedron();
SurfaceMesh trimesh;
trimesh.assign(polymesh);
SurfaceTriangulation(trimesh).triangulate();
// do stuff with the triangles
```
