### ISSUE TITLE
Parameterization

### ISSUE THREAD

**Issue by breakerrorchen** [pmp-library/pmp-library#113]
Parameterization of PMP requires grid to have boundary points. If you have a closed mesh, like a cube, how can you parameterize it automatically？

**Comment by dsieger** [comment]
Sorry, we currently don't have such functionality. The following paper might be interesting for you:

* Paper: https://www.cs.cmu.edu/~kmcrane/Projects/CEPS/index.html
* Code: https://github.com/MarkGillespie/CEPS

**Comment by breakerrorchen** [comment]
@dsieger thanks
