### ISSUE TITLE
The output mesh of triangulation test with max_angle is wrong.

### ISSUE THREAD

**Issue by schneider007** [pmp-library/pmp-library#116]
In the second test function of SurfaceTriangulationTest.cpp of project gtest_runner, output the triangulation result with:
mesh.write("D:\\mesh.obj");

Open the result obj file, it looks like this:
![image](https://user-images.githubusercontent.com/8435686/184613181-ba6c3e5d-e067-46ed-af6e-89edcc1b5361.png)

**Comment by dsieger** [comment]
This works as expected: The function only maximizes the minimum angle and nothing else. It does not prevent flips from happening. See also #95
