### ISSUE TITLE
Some problem about the Linear Algebra module

### ISSUE THREAD

**Issue by XuRongYan** [pmp-library/pmp-library#12]
Hi,
I wanted to use your library to implement some algorithm. But I found that I can't input the matrix in the same way as Eigen.
```
Matrix3i m1;
m1 << 1, 2, 3,
      4, 5, 6,
      7, 8, 9;
```
And I can't find any methods in the API document. Can you please tell me if there is an elegant approach to input the matrix ?
Furthermore, I want to know that how to create a m * n matrix?
Thank you for your help.

**Comment by dsieger** [comment]
Hi,

We currently don't provide an API similar to Eigen for our matrix classes. They are rather specialized for the use in our viewer classes. For general matrix computations, I'd suggest to simply use Eigen directly. Note that we might consider replacing our custom classes with the Eigen ones in the future.

Regards,
Daniel

**Comment by XuRongYan** [comment]
Hi, 
Thank you for your advice. I pretty expect this update. And I very like this library. Thank you for your nice work.

**Comment by mbotsch** [comment]
Hi,
we added a new constructor for the matrix/vector class using the syntax of C++11 initializer lists. Now you can write the following row-wise initialization:

mat3 m33{1, 2, 3,
                 4, 5, 6,
                 7, 8, 9};

Or for non-square matrices:

Matrix<int,2,3> m23{1, 2, 3,
                                4, 5, 6};

Please note, however, that for serious linear algebra stuff it is better to use Eigen. Our internal matrix/vector class is there basically for OpenGL transformation, and to avoid ugly template error messages. We tried to have our matrix/vector class and its operators to be compatible to GLSL syntax, which makes it somewhat more intuitive to use than Eigen.

Best
Mario
