### ISSUE TITLE
LSCM: Failed solve linear system

### ISSUE THREAD

**Issue by aTerminal** [pmp-library/pmp-library#121]
**Describe the bug**
When using pmp-library to perform LSCM parameterization on a tooth model generated from a point cloud, the problem shown in the figure below occurs.
**Parameterization: Failed solve linear system.**

**To Reproduce**
1. Download the mesh from here: 
[UpperJaw_Gen.zip](https://github.com/pmp-library/pmp-library/files/9575444/UpperJaw_Gen.zip)
2. Drag and drop the ply file in the compressed package to parameterization.exe after compilation
3. See error

**Expected behavior**
The model should be parameterized by the LSCM algorithm.

**Screenshots**
![Figure 1](https://user-images.githubusercontent.com/47311923/190410726-2f5a6ef9-19e1-427b-bcde-3efcdac0b3cd.png)

**Environment (please complete the following information):**
 - OS: Microsoft Windows 10
 - Compiler: Visual Studio 2017
 - Build type: Release

**Additional context**
This model can be read by pmp-library, so it should be manifold, but it cannot be parameterized by pmp-library's two parameterization methods. Are there other constraints that prevent the parameterized process?

Thank you for your help!

**Comment by dsieger** [comment]
Looks like the mesh contains multiple disconnected components, holes, and very low quality triangles. Examples:

![image](https://user-images.githubusercontent.com/6951585/190443085-b1f21289-3ee4-4cee-a98d-a38bf8f06ce9.png)

![image](https://user-images.githubusercontent.com/6951585/190443005-4e0e62af-3754-43a6-926c-f5b03188f876.png)

![image](https://user-images.githubusercontent.com/6951585/190442915-f7b47018-37b3-46ef-a099-d15e66d5579d.png)

I'm afraid you won't be able to parameterize this without some serious pre-processing, i.e., removing isolated components, fill the small holes, and eventually do some remeshing.

Hope this helps!
