### ISSUE TITLE
Get the uv coordinates of a mesh

### ISSUE THREAD

**Issue by LeHibou2** [pmp-library/pmp-library#122]
Hi!

Is the following code correct to get the uv texture mapping of each vertices of a given triangulated shape?

```
pmp::SurfaceMesh mesh;

// add vertices ...

pmp::SurfaceTriangulation tri( mesh );

tri.triangulate();

pmp::SurfaceParameterization param( mesh );

param.lscm();

auto tex = mesh.vertex_property <pmp::TexCoord> ( "v:tex" );

for ( auto e : mesh.faces() ){

        for ( auto vertex_index : mesh.vertices( e ) ){

                auto point2d = mesh.position( vertex_index );
                span <float> i( tex[vertex_index].data(), 2 );
                float  uv_coords_x = i[0];
                float  uv_coords_y = i[2];

        }
}
```

Not sure, that's why I ask..

Thanks!

**Comment by dsieger** [comment]
This looks more complicated than needed. You can just iterate over all vertices and then access the texture coordinates directly. `pmp::TexCoord` is just a 2D vector, so you can access it with `operator[]`. Something like that:

```cpp
auto tex = mesh.vertex_property<TexCoord>("v:tex");
for (auto v : mesh.vertices())
{
    std::cout << "uv_x: " << tex[v][0] << std::endl;
    std::cout << "uv_y: " << tex[v][1] << std::endl;
}
```

Hope this helps.

**Comment by LeHibou2** [comment]
Thanks Daniel,

And what is the best way to retrieve each triangle of the mesh?
On the basis of what i read in your source, I will have to check every connected edge from the mesh and check for the edge of the two other points, like you do in `bool SurfaceTriangulation::insert_edge(int i, int j)`.
Maybe we could add a structure that holds the triangles?

**Comment by dsieger** [comment]
Just iterate over all faces and then get all points of that face:

```cpp
 for (auto f : mesh.faces())
    for (auto v : mesh.vertices(f))
            std::cout << "point: " << mesh.position(v) << std::endl;
```

**Comment by LeHibou2** [comment]
Nice :)

Thanks Daniel
