### ISSUE TITLE
specify polygon holes

### ISSUE THREAD

**Issue by LumiereDeLOmbre** [pmp-library/pmp-library#124]
Hi,
I use the Boost geometry library and I have polygons with holes I want to keep.

Think of a square with a smaller square inside in its center that represents a hole.

It would be nice to be able to tell pmp that a polygon is a hole to make sure that it won't be messed up.

We have add_face, maybe something like add_hole would be nice to have (and maybe simpler for the algorithms)?

Or what is the best current way to do it properly? 

Thanks

**Comment by dsieger** [comment]
Our representation does not allow for polygons with holes. I don't think an extension would be straightforward and I don't have a use case for this. Your best chance is probably to triangulate the polygon so that you can import it as a mesh with boundary.

**Comment by LumiereDeLOmbre** [comment]
@dsieger I thought that maybe a boolean associated to a vertice, telling to not touch it for connection, or disable a triangle that has three of them activated.

What do you think about it?

It would be the most trivial way to accept holes.
When adding a vertice, a boolean could be given to specify the vertice.

No need to modify the algorithms, maybe just add a last pass to remove the triangles with 3 activated booleans.

Overall the performance should not be that bad.

**Comment by LumiereDeLOmbre** [comment]
And for decimation, only one boolean would make it illegal to touch the whole edge.

**Comment by LumiereDeLOmbre** [comment]
https://github.com/pmp-library/pmp-library/blob/main/src/pmp/SurfaceMesh.h#L33

We could make use of reset() and is_valid() : we don't need to touch any other structure..
