### ISSUE TITLE
why “Remove SurfaceMesh::edge_length()” ？

### ISSUE THREAD

**Issue by summer-go** [pmp-library/pmp-library#125]
hi, why remove SurfaceMesh::edge_length()? is there another function to use ?

**Comment by dsieger** [comment]
As mentioned in the commit message: The function is trivial and has no reason to be a member function of the `SurfaceMesh` class. The `SurfaceMesh` API already has a large number of member functions and I want to keep it to a minimum. You can easily get the edge length using already existing public member functions:

```cpp
norm(mesh.position(mesh.vertex(e, 0)) - mesh.position(mesh.vertex(e, 1)));
```

If people think that it would be useful to wrap this in a convenience function and put it into `utilities.h` or similar, I'd be happy to reconsider.

**Comment by dsieger** [comment]
FYI: d171ee5

Sorry this took so long.
