### ISSUE TITLE
Custom vertex buffer support

### ISSUE THREAD

**Issue by Zeta48** [pmp-library/pmp-library#127]
I am looking for a mesh decimation library to add LOD system to my engine.
Would it be possible to add vertex attributes support to PMP? For instance my engine vertices consist of:
`
 
	struct Vertex
	{
		Math::Vec3 position;
		Math::Vec3 normal;
		Math::Vec3 tangent;
		Math::Vec3 bitangent;
		Math::Vec2 texCoord;
	};
	
`

Thank you!

**Comment by dsieger** [comment]
You can add arbitrary properties to the entities of a `SurfaceMesh`. See the [Dynamic Properties](https://www.pmp-library.org/tutorial.html#autotoc_md63) section of the tutorial.

Our `Decimation` class supports to control deviation of certain mesh attributes such as normal deviation or preservation of texture seams. Please have a look at the [docs](https://www.pmp-library.org/classpmp_1_1_decimation.html) to check if that fits your need.
