### ISSUE TITLE
Function that converts x,y,z vector coordinates to spherical coordinate system

### ISSUE THREAD

**Issue by janvda** [pmp-library/pmp-library#133]
**Is your feature request related to a problem? Please describe.**
I would like to print the *spherical coordinates* of the vertices of my mesh instead of the cartesian coordinates.
* https://en.wikipedia.org/wiki/Spherical_coordinate_system

**Describe alternatives you've considered**
I am considering to implement the formulas myself in C++

![image](https://user-images.githubusercontent.com/17238398/208143783-086d69a9-9162-4680-bf61-7a7087a82a13.png)

**Additional context**
NA

**Comment by dsieger** [comment]
Thanks for your suggestion, but I don't really have a use case for such a function at the moment. You already have the formulas, so coming up with your own implementation should be relatively straightforward.

**Comment by janvda** [comment]
Indeed it was not that hard to implement it myself using above formulas

```
              for (auto v : mesh_.vertices(f))
              {
                  	double r, theta, phi, sign_y;
                  	double x1 = mesh_.position(v)[0];
		            double y1 = mesh_.position(v)[1];
                    double z1 = mesh_.position(v)[2];
		            double xsq = x1 * x1;
		            double ysq = y1 * y1;
		            double zsq = z1 * z1;
		            r = sqrt(xsq + ysq + zsq);
                    sign_y = (0 < y1) - ( y1 < 0 );
		            theta = acos( z1/r );
		            phi = sign_y * acos( x1 / sqrt( xsq + ysq));
                   std::cout << "point: " << mesh_.position(v) << std::endl;
                   std::cout << "r = "<< r <<", theta = "<< theta <<", phi = " << phi << std::endl;
              }
```
