### ISSUE TITLE
Add an 'add_faces' method

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [pmp-library/pmp-library#134]
**Is your feature request related to a problem? Please describe.**
I'm converting existing meshes from Rhino to a pmp SurfaceMesh. Currently, the only obvious way of doing this is manually adding vertices and creating faces:

```c++
verts.reserve(vertexFloatArray.size() / 3);   
 for (int i = 0; i < vertexFloatArray.size(); i += 3)
    {
           verts.push_back(mesh.add_vertex(Point(vertexFloatArray[i], vertexFloatArray[i + 1], vertexFloatArray[i + 2])));
    }
    
    for (int i = 0; i < facesArray.size(); i += 3)
    { 
        mesh.add_triangle(verts[(facesArray[i])], verts[(facesArray[i + 1])], verts[(facesArray[i + 2])]);
    }
```
The `add_face` method, however, is relatively slow because of all the internal checks it has to perform.

**Describe the solution you'd like**
An `add_faces` method, where one could provide a vector of faces and they would be all added at once.

**Describe alternatives you've considered**
I looked into how a pmp mesh is read in the `read_pmp` method, specifically this part:
https://github.com/pmp-library/pmp-library/blob/2894329d542df8707128dd39c59ad2e2b4c7808e/src/pmp/io/read_pmp.cpp#L38-L41

It looks like I could define these relationships based on Rhino's mesh connectivity and pass them directly to the mesh. What are the required inputs for each of the categories, though? Are the below assumptions correct?

Point -> X, Y, Z (float)
FaceConnectivity -> VertexA, VertexB, VertexC (int indices)
HalfedgeConnectivity -> VertexFrom, VertexTo  (int indices)
VertexConnectivity -> ?

**Comment by dsieger** [comment]
I understand the motivation of your request. However, such a function would leak the internal implementation details of the class and therefore completely break [encapsulation](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)). I will not add anything like that. `add_face` and friends are there for a reason, i.e., to ensure internal consistency of the data structure.

**Comment by mariuszhermansdorfer** [comment]
Thanks for explaining the rationale behind your decisions @dsieger. I understand that you don’t want this to be part of the official library, but I’d still like to add it to my wrapper to speed up communication with Rhino. 

In principle, it would be the same mechanism as you use for reading pmp files. I’d like to operate on byte arrays and pass these directly to the corresponding connectivity declarations. 

Hence my question above - could you please explain how the following data arrays should be structured to satisfy the requirements of the SurfaceMesh class?

Point
FaceConnectivity
HalfedgeConnectivity
VertexConnectivity

I’d appreciate your help!

**Comment by dsieger** [comment]
Well, you've got the definitions of the connectivity structs available in `SurfaceMesh.h`. That's the information we store for each entity and it would be up to you to make sure that all of those indices point consistently to their neighbors and adjacent entities.

For more information about the data structure see the [tutorial](https://www.pmp-library.org/tutorial.html) and the original [SurfaceMesh paper](http://dx.doi.org/10.1007/978-3-642-24734-7_29) ([pdf](https://www.danielsieger.com/download/imr11.pdf)).

However, unless Rhino uses a very similar data structure internally (and gives you access to those details) I think you will have a hard time trying to achieve what you have in mind. Good luck!

**Comment by mariuszhermansdorfer** [comment]
Thanks.
does the order of data in the HalfedgeConnectivity byte array follow the order of entries in the struct definition?
![image](https://user-images.githubusercontent.com/49192999/208266522-15d2d418-1329-4bf8-b39e-67c5e5db256f.png)

Rhino's Mesh doesn't support halfedges, but these can be derived from face/edge/vertex relationships easily accessible in the API. Just to be sure - a face only points to one halfedge, correct? Is this an arbitrary assignment? I.e. any halfedge (h, h0, h1) can be chosen as long as they are defined in the counter-clockwise direction.

![image](https://user-images.githubusercontent.com/49192999/208267350-458f1900-50c8-4330-b613-45ca097bf925.png)

**Comment by dsieger** [comment]
> Thanks. does the order of data in the HalfedgeConnectivity byte array follow the order of entries in the struct definition? !

Yes, that's basically just the underlying data array of a `std::vector<HalfedgeConnectivity>`.

> Rhino's Mesh doesn't support halfedges, but these can be derived from face/edge/vertex relationships easily accessible in the API. Just to be sure - a face only points to one halfedge, correct? Is this an arbitrary assignment? I.e. any halfedge (h, h0, h1) can be chosen as long as they are defined in the counter-clockwise direction.

Yes and yes.

> I'll give it a shot and see whether there is any performance benefit to doing things this way as opposed to just calling add_face multiple times.

Let me know how it goes, I'm curious!

**Comment by mariuszhermansdorfer** [comment]
Thanks @dsieger, I'll keep you posted on my progress.

While reading your paper, this section caught my attention:
>Since opposite halfedges are laid out consecutively in memory, the opposite halfedge can be accessed by simple modulo operations on the Halfedge indices and therefore does not have to be stored explicitly.

Does this mean that the `std::vector<HalfedgeConnectivity>` for this diagram has the following structure?
```c#
{h, h2, h0, h3, h1, h4}
```
or can it be laid out like this?

```c#
{h, h0, h1, h2, h5, h6}
```

![image](https://user-images.githubusercontent.com/49192999/208430647-0c9926a8-e9fd-4049-ab49-bf798f6aee61.png)

**Comment by dsieger** [comment]
> Thanks @dsieger, I'll keep you posted on my progress.
> 
> While reading your paper, this section caught my attention:
> 
> > Since opposite halfedges are laid out consecutively in memory, the opposite halfedge can be accessed by simple modulo operations on the Halfedge indices and therefore does not have to be stored explicitly.
> 
> Does this mean that the `std::vector<HalfedgeConnectivity>` for this diagram has the following structure?
> 
> ```cs
> {h, h2, h0, h3, h1, h4}
> ```

Yes, that should be it.
