### ISSUE TITLE
Calling triangulate corrupts faces

### ISSUE THREAD

**Issue by Revln9** [pmp-library/pmp-library#135]
**Describe the bug**
Calling triangulate on a  mesh will corrupt the vertex order and it will show up without faces. 

**To Reproduce**
```

#define _USE_MATH_DEFINES
#include <iostream>
#include <pmp/SurfaceMesh.h>
#include <pmp/algorithms/Remeshing.h>
#include <pmp/io/io.h>
#include <pmp/utilities.h>
#include <pmp/algorithms/Triangulation.h>
#include <string>


using namespace pmp;


int main(int argc, char* argv[])
{
    SurfaceMesh mesh;
    read(mesh, argv[1]);
    float num = std::stof(argv[2]);
    try
    {
        Triangulation tr(mesh);
        tr.triangulate( pmp::Triangulation::Objective::MIN_AREA);
        auto bb = bounds(mesh).size();
        Remeshing(mesh).adaptive_remeshing(
            num * bb,  // min length
            0.0500 * bb,  // max length
            0.0005 * bb); // approx. error
        write(mesh, "output.obj");
    }
    catch (const InvalidInputException& e)
    {
        std::cerr << e.what() << std::endl;
        return 0 ;
    }

    

    std::cout << argv[2] << argv[1] << std::endl;
    return 0;
    }


```
![blender_iWhkLhtdzG](https://user-images.githubusercontent.com/8087021/210260494-17355b30-0b83-482d-9b42-ae156bded7ac.jpg)

Any solution to this ? 

Thanks

**Comment by dsieger** [comment]
Can you share the mesh?

**Comment by Revln9** [comment]
Sure, here is the link: 
[dress.obj](https://drive.google.com/file/d/1PXW1R5Lf0Hqx7WCibUGJbt3WWdFyfKa_/view?usp=sharing)

I tried doing the same steps with the same file using mpview and it works without problem. Didn't export it tho. So maybe it's an export issue

![mpview_Prjwiy2XtD](https://user-images.githubusercontent.com/8087021/210271953-7b71471f-efba-466a-b824-eaa6c927c171.jpg)

Thanks

**Comment by dsieger** [comment]
Your input mesh has some texture coordinates per halfedge which are not preserved by triangulation and remeshing. Removing those after reading the mesh resolves the issue:

```cpp
auto tex_coords = mesh.get_halfedge_property<TexCoord>("h:tex");
if (tex_coords) {
    mesh.remove_halfedge_property(tex_coords);
}
```

Running your example code with `0.005` as second parameter gives the following mesh:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/6951585/210441991-6a619a6b-5234-4341-94ed-6dccecacb7c9.png">

**Comment by dsieger** [comment]
Yes, there's more on the roadmap, most notably a polygon laplacian and deformation transfer. We talked about quad meshing from time to time. This would be a great addition, but we did not do any concrete steps in that direction so far.
