### ISSUE TITLE
Question: Texture Coordinate support

### ISSUE THREAD

**Issue by jtorresfabra** [pmp-library/pmp-library#14]
Hi, 

Sorry if it is not a feature request or a bug, more a question. 

First of all just wanted to congratulate you for the work on PMP book and library (I own a paper version of the book). 

Second, I'm wondering what kind of texture support  (if any) you have for the decimator. meaning support for uv's, seam detection/blcoking, boundaries etc. 
I'm using OpenMesh right now with partial success, it is quite good for decimation but I also need also parametrization and OpenMesh does not have it.  

Does PMP-library support texture coords in simplification?
Thanks!

**Comment by mbotsch** [comment]
We currently do not pay attention to texture coordinates during decimation, but basic support should not be hard to add, so we could implement it in the near future. We could make sure that texture seams are detected and not messed up during decimation. Would this be what you are thinking of?

**Comment by jtorresfabra** [comment]
Yeah, mainly having into account texture seams. There are several methods to implement it though. Just in case you want some references (Probably you already know but... here we go) maybe this one is near the state of the art https://github.com/songrun/SeamAwareDecimater. 

Thanks.

**Comment by TheOriginalBytePlayer** [comment]
Has there been any progress on adding texture coordinate awareness?  Also, @jtorresfabra , if you don't mind? what does the SeamAwareDecimator lack that pmp-library is offering?

**Comment by dsieger** [comment]
> Has there been any progress on adding texture coordinate awareness?

I think @mbotsch or one of his PhD students was looking into this. Any updates Mario?
