### ISSUE TITLE
Build static library

### ISSUE THREAD

**Issue by ramcdona** [pmp-library/pmp-library#140]
Is there a way to build a static library version of pmp-library?

Also, is there a mailing list, forum, or other place to ask users/developers questions about pmp-library?  It seems that the Issue tracker is the only way to communicate with anyone about the project -- and that does not seem like the best use of the issue tracker.

**Comment by dsieger** [comment]
Have a look at https://github.com/pmp-library/pmp-library/blob/ceb125bc9efdecd77f3c9df1296f21b75b8a2ba2/src/pmp/CMakeLists.txt#L7 

Changing this to
```cmake
add_library(pmp STATIC ${SOURCES} ${HEADERS})
```
will build a static library. Using CMake's [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html#variable:BUILD_SHARED_LIBS) global option might be the right thing to do in the future.

Regarding your second question: There currently is no mailing list or forum. I was thinking about opening up Discussions here on GitHub, though. I agree that it would be better to reserve the issue tracker for real issues only.

Hope this helps!

**Comment by ramcdona** [comment]
Thanks for that pointer, I'll check it out.

If it works out, I'll try to add a build option and some documentation in the web site.  I'll also add documentation for the PMP_BUILD_(APPS, EXAMPLES, TESTS, DOCS, VIS) options while I'm at it.

I would encourage the creation of some sort of way for users to communicate (and adding it to the website near Contributing and other such places).
