### ISSUE TITLE
Un-Split edge

### ISSUE THREAD

**Issue by ramcdona** [pmp-library/pmp-library#143]
Is there a method to 'un-split' an edge?  Similar to the edge remove and triangles, but for nodes and edges?  I see the SurfaceMesh::split(e,v) method -- and I basically want something to un-do that operation.

In my program, I start with quad meshes (in my own data structures) that overlap.
![step1](https://user-images.githubusercontent.com/1329600/224256915-840ce9fe-4044-4ab0-926a-509718a3b513.png)

I then drop in diagonals to convert the quads to tris and perform a CSG Boolean Union (my own algorithms).
![step2](https://user-images.githubusercontent.com/1329600/224257153-87a2c76d-7126-47a9-9945-9b119e930365.png)

I now put the tris into PMP's data structures.  I pass along a property that identifies which quad each tri originated from -- this was propagated through all of the CSG operations.  Using that information, I can use SurfaceMesh::remove_edge() to clean up the mesh.
![step3](https://user-images.githubusercontent.com/1329600/224257524-8945c57b-39bf-44d7-8e42-62af2064d948.png)

Which is great progress.  However, the intersection edges often have un-needed nodes which are left-over from where the diagonals intersected the opposing tris.  I.e.
![step4](https://user-images.githubusercontent.com/1329600/224257753-ea83c8c1-5a42-413b-b9fa-3e6e3e59eedd.png)

The edges before/after these extra nodes will be co-linear to a tight tolerance.  I would like to iterate over edges, look for e1,e2 pairs who share the same faces on each side (and possibly other criteria including co-linearity) and then merge them together.

As an alternative, I might search for the longest chain of edges with the same left/right faces -- then do my comparison for how far the intermediate vertices fall from the line from start to end of the chain...  Either way, I'll need to remove verts and merge edges.

I don't see this operation in the API already -- am I missing something, or is it not implemented yet?

**Comment by dsieger** [comment]
You are basically looking for an edge collapse. However, not the standard one we have, but a variant that allows to remove superfluous edges in polygonal faces without removing incident faces. Interesting case. Don't think we have that operation, but should be relatively straightforward to implement.

**Comment by ramcdona** [comment]
OK, thanks.  I may take a stab at trying to figure it out.  Good to confirm that I'm not overlooking something.
