### ISSUE TITLE
Triangulate non-convex polygons

### ISSUE THREAD

**Issue by ramcdona** [pmp-library/pmp-library#144]
Does the triangulate algorithm work properly for non-convex polygons?

I could find no such limitation in the documentation -- so I assumed it would work properly.  However, I'm now running into an issue that looks like it is because of how triangulation reacts to my polygon.

**Comment by dsieger** [comment]
Which objective function are you using? `min_area` or `max_angle`? What's the issue exactly? Could you provide an example to reproduce?

**Comment by ramcdona** [comment]
I had initially run with MAX_ANGLE.  Switching to MIN_AREA has fixed the problem.

Here is an example of my polygon.
![Outline](https://user-images.githubusercontent.com/1329600/224455685-f0acc723-7f60-432d-8dc5-77931d102e5a.png)

Here is the result when run with MAX_ANGLE.
![Bad](https://user-images.githubusercontent.com/1329600/224455700-271c4504-9692-4850-863b-1e2b9e644d33.png)

And here is the desired result achieved by running with MIN_AREA
![Good](https://user-images.githubusercontent.com/1329600/224455722-31952886-58b0-4d82-b6fa-4b3f42336b96.png)

I do not have the ability to isolate this polygon right now.  I can keep working on it, but I suspect this will give you enough to work on it.

The polygon points are coplanar -- but the plane is arbitrarily oriented in 3D.  I suspect the extra nodes along the border are what is throwing things off.

**Comment by dsieger** [comment]
Users have run into this in the past when using the `max_angle` objective, see #116 and #95. I'll add some warning to the documentation.

**Comment by ramcdona** [comment]
Thanks.  I think some documentation updates will go a long way.  You might also consider changing the examples to demonstrate the other algorithm.  I expected them to behave essentially the same (in my application, I don't care about some nuance of triangle quality, so I had no reason to prefer one over the other).  So I just copy/pasted from the example.

I.e. the case used in the examples becomes a de-facto recommendation for naive users like me.

**Comment by dsieger** [comment]
Which example are you referring to? As far as I can tell all examples use the default `triangulate()` function without specifying an objective function, thereby using the min area objective as default argument (there's a reason why we chose this one as default argument).

Anyway, I totally agree that having more visual examples for the different algorithms and their parameters would be nice to have.

**Comment by ramcdona** [comment]
I can't find any such example now -- I can only find the unit tests, where both are tested side-by-side.  Perhaps I flipped a coin there...
