### ISSUE TITLE
Is there any easily way to implement the inverse transformation of an edge collapse? 

### ISSUE THREAD

**Issue by zoujieJason** [pmp-library/pmp-library#15]
I try to use function delete and function add to implement, but I encountered some problems:
`for(const auto &face: mesh.faces(pmp::Vectex(0)) { 
    mesh.delete_face(face);
}`
it does not work, also as I store all the faces and then deleted them.

**Comment by mbotsch** [comment]
The inverse operation of an edge collapse is the vertex split. We (accidentially?) removed this functionality when converting from OpenMesh to SurfaceMesh some years ago, and did not re-introduce it when moving on to the pmp-library.

The implementation is unfortunately not very straightforward. You can find the OpenMesh version of it in the functions `vertex_split`, `insert_loop`, and `insert_edge` in the file [TriConnectivity.cc](https://graphics.rwth-aachen.de:9000/OpenMesh/OpenMesh/blob/master/src/OpenMesh/Core/Mesh/TriConnectivity.cc).

What is the functionality that you need?

**Comment by zoujieJason** [comment]
Thank you for your reply, but I wanna ask you another problem:
How to exchange to two vertex's topology directly？

**Comment by dsieger** [comment]
Closing as original question was answered.
