### ISSUE TITLE
How can I convert SurfaceMesh to a simple OpenGL VAO?

### ISSUE THREAD

**Issue by jkooooo99** [pmp-library/pmp-library#150]
Sorry to bother you, but I was wondering if there is an "officially recommended", clean way to convert `SurfaceMesh` to OpenGL VAO?

My own OpenGL codes are basically a poor copy of the "LearnOpenGL" tutorial (I'm a  newbie).
![1](https://user-images.githubusercontent.com/81244845/230734170-6df48a4d-035b-48ff-b563-f7085fe95407.JPG)

And I'm so used to using so-called "Modern OpenGL" that all my glDraw is `glDrawElements`...
![3](https://user-images.githubusercontent.com/81244845/230734238-504a029a-723d-4205-b80e-995060d04b7c.JPG)

I also tried to look at the codes for `update_opengl_buffers()` of the `SurfaceMeshGL`, but it's too complicated to get started (I can only understand `glDrawArrays(GL_TRIANGLES, 0, n_vertices_)`, sorry I'm a newbie!) ...

Is there a simple and straightforward way to throw vertex, normal, UV, and index directly into a "plain" std::vector<float/int>?
That way I can render the model myself instead of using this extremely awkward method...
![2](https://user-images.githubusercontent.com/81244845/230734251-a34f7bee-d31d-439d-8918-6e42e7bebd05.JPG)

**Comment by dsieger** [comment]
Hi,

Answering your original question about a straightforward way to get a `std::vector` for any property: There's a function aptly named `vector()` to get access to the underlying vector:

```cpp
auto mesh = pmp::icosphere(0);
auto points = mesh.get_vertex_property<Point>("v:point");
const auto& vec = points.vector();

for (auto v : vec) {
    std::cerr << v << std::endl;
}
```

Hope this helps to simplify your solution!
