### ISSUE TITLE
`centroid` call inside `quad_tri_subdivision` operates on the wrong number of face vertices

### ISSUE THREAD

**Issue by mokafolio** [pmp-library/pmp-library#156]
**Describe the bug**
Bug is visually hard to spot but becomes pretty evident if you remove the moving of the vertices post subdivision. The centroid call inside `quad_tri_subdivision` operates on the wrong number of face vertices. Here is the relevant source code in `subdivision.cpp` line 376:

```            
// quadrangulate the rest
Halfedge h0 = mesh.halfedge(f);
Halfedge h1 = mesh.next_halfedge(mesh.next_halfedge(h0));
h1 = mesh.insert_edge(h0, h1);
mesh.insert_vertex(mesh.edge(h1), centroid(mesh, f));
```

`insert_edge` will modify the vertex count of the current face, resulting in a wrong result for the following `centroid` call. This will fix it:

```            
// quadrangulate the rest
Halfedge h0 = mesh.halfedge(f);
Halfedge h1 = mesh.next_halfedge(mesh.next_halfedge(h0));
auto cen = centroid(mesh, f);
h1 = mesh.insert_edge(h0, h1);
mesh.insert_vertex(mesh.edge(h1), cen);
```

**To Reproduce**
Use the `quad_tri_subdivision` function.

**Expected behavior**
That the extra vertex is the correct centroid.

**Screenshots**
wrong
<img width="650" alt="Screenshot 2023-05-18 at 1 07 21 PM" src="https://github.com/pmp-library/pmp-library/assets/10217168/dd32b32f-4e41-4ec6-9271-d8f4de405d74">

correct
<img width="650" alt="Screenshot 2023-05-18 at 1 08 05 PM" src="https://github.com/pmp-library/pmp-library/assets/10217168/527dbb86-09b5-4345-b549-a402cc279ff7">

**Environment (please complete the following information):**
 - OS: osx
 - Compiler: clang
 - Build type: Debug

**Comment by dsieger** [comment]
Good catch!
