### ISSUE TITLE
Improve the API returning success/error values

### ISSUE THREAD

**Issue by jtorresfabra** [pmp-library/pmp-library#16]
I'm trying pmp-library, and while seems easy to setup and start using the lib in my own code I have some issues with the API. Maybe I'm missing something but to be more exact:

https://github.com/pmp-library/pmp-library/blob/master/src/pmp/algorithms/SurfaceParameterization.h#L35-L38

There is no way to know if the parametrization failed or succeed. (In my case it is failing sometimes). Would be nice to have a boolean return parameter or similar (error enum etc) to know the result state. 

Thanks

**Comment by dsieger** [comment]
Hi,

Thanks for your feedback. Indeed, the lack of consistent error reporting has been bugging me for a while, too. I'd probably go for exceptions, though. Marking this as a feature enhancement.

**Comment by dsieger** [comment]
Exceptions are now merged into `master`.
