### ISSUE TITLE
Issue with STL reader

### ISSUE THREAD

**Issue by alejandro-machina** [pmp-library/pmp-library#170]
**Describe the bug**
How bulletproof is the `read_stl()` function? I have a STL file that loads fine in out-of-the-box software (like blender, meshlab, etc) and some other C++ libraries (like libigl, assimp, etc) but when trying to use it in pmp the mesh is not read. I dig a little into the code and seems the lines that the reader decides if a file is binary or ascii are hit incorrectly for that specific mesh
![image](https://github.com/pmp-library/pmp-library/assets/134331880/2b741012-b9bf-42df-a623-595eac7cc5d2)

Other meshes I have for testing seem to work fine on pmp. The specific STL is added here for you to check.
[part.zip](https://github.com/pmp-library/pmp-library/files/12176491/part.zip)

**To Reproduce**
1. Compile normally the pmp library (usual cmake and make)
2. Run the example of mpview with argument part.stl, i.e. `mpview part.stl`
3. The viewer runs fine but no mesh is in scope, and data says no vertices, no edges, no faces 
![image](https://github.com/pmp-library/pmp-library/assets/134331880/9366c2d2-6f76-4cf8-bcb3-7be1374842ce)

**Expected behavior**
Here is the viewer with the mesh (which is what I am expecting). To do this I just changed the above line of binary to be hit always (I know that part.stl is binary)
![image](https://github.com/pmp-library/pmp-library/assets/134331880/2f4d4f10-7da4-401b-b7ee-c89e059ea49d)

**Environment (please complete the following information):**
 - OS: Windows
 - Compiler: Visual Studio 2022 (vc17 I believe)
 - Build type: Both (Debug and Release)

**Additional context**
I also tested on ubuntu with gcc (via WSL) and same up to no showing the mesh when loaded, haven't modify the binary flag in that environment to verify the mesh will show but most likely that is the case

**Comment by dsieger** [comment]
Hah, interesting case! Your analysis is correct that the test for a binary file fails in this case. The reason is that the provided STL file begins with the ASCII characters `solid Part`. According to [Wikipedia](https://en.wikipedia.org/wiki/STL_(file_format)) this is generally a no-go for binary STL files:

> A binary STL file has an 80-character header which is generally ignored, but should never begin with the ASCII representation of the string solid, as that may lead some software to confuse it with an ASCII STL file.

Nevertheless, would be good if our STL reader would be more robust for such cases.

Out of curiosity: Which software created the STL file?

**Comment by alejandro-machina** [comment]
ahhh, thanks for the answer ... helps me to also pay attention about that with other geometries.

The file was provided to me and I never asked how was created but from the workflow of my current job it is usually do in 2 ways to get a mesh (the initial input is a CAD file)

1. Use out-of-the-box CAD software like solidworks or rhino and let that software do the import to STL
2. In C++ we plugin this gigantic library https://dev.opencascade.org/doc/overview/html/ to our pipeline which can convert CAD/Nurbs into STL/Faces

**Comment by dsieger** [comment]
I see, thanks.

I'll keep the issue open as a reminder to make our binary detection more robust.
