### ISSUE TITLE
STL export does not guarantee positive vertex coordinates

### ISSUE THREAD

**Issue by dsieger** [pmp-library/pmp-library#172]
According to the original STL spec the vertex coordinates should all be in the positive octant. See also: https://www.fabbers.com/tech/STL_Format

**Comment by Nosenzor** [comment]
Wow ! First time in 25 years I'm hearing that... but that's true it is written in "specs" :

"The object represented must be located in the all-positive octant. In other words, all vertex coordinates must be positive-definite (nonnegative and nonzero) numbers. The StL file does not contain any scale information; the coordinates are in arbitrary units.

The official 3D Systems StL specification document states that there is a provision for inclusion of “special attributes for building parameters,” but does not give the format for including such attributes. Also, the document specifies data for the “minimum length of triangle side” and “maximum triangle size,” but these numbers are of dubious meaning. "

Nevertheless I don't know any "decent" stl exporter/importer that won't support negatives values!!

**Comment by dsieger** [comment]
Probably safe to ignore the spec. Closing.
