### ISSUE TITLE
remnants of submodules

### ISSUE THREAD

**Issue by malytomas** [pmp-library/pmp-library#175]
**Describe the bug**
executing `git submodule update init --recursive` on a repository that contains pmp as a submodule tries to load `external/eigen` and fails with error:
`fatal: No url found for submodule path 'externals/pmp/pmp/external/eigen' in .gitmodules`
`fatal: Failed to recurse into submodule path 'externals/pmp/pmp'`

**Environment (please complete the following information):**
 - OS: windows and linux (tested on github actions and locally)

**Additional context**
please remove the references for the submodules - the apparent folders

**Comment by dsieger** [comment]
pmp itself does not contain submodules anymore. Did you try `git clean -ffd` in the top-level pmp directory? See also #167

**Comment by malytomas** [comment]
This has happened to me in completely clean git clone.
