### ISSUE TITLE
missing faces in face circulator

### ISSUE THREAD

**Issue by chaohuang** [pmp-library/pmp-library#176]
I use pmp to read a triangle mesh, then I find that the number of incident faces from the face circulator around a vertex is different from the number of faces incident to that vertex.

The code I use is:

    pmp::SurfaceMesh mesh;
    pmp::read(mesh, "testMesh.obj");

    pmp::Vertex currVert(1318);
    int32_t faceCount = 0;
    for (auto const& face : mesh.faces(currVert)) {
      std::cout << "face " << face.idx() << ":";
      for (auto const& v : mesh.vertices(face)) {
        std::cout << " " << v.idx();
      }
      std::cout << "\n";
      ++faceCount;
    }

    std::cout << "Vertex 1318 has " << faceCount << " incident faces\n\n";

    faceCount = 0;
    for (auto const& face : mesh.faces()) {
      for (auto const& vert : mesh.vertices(face)) {
        if (vert.idx() == 1318) {
          std::cout << "face " << face.idx() << ":";
          for (auto const& v : mesh.vertices(face)) {
            std::cout << " " << v.idx();
          }
          std::cout << "\n";
          ++faceCount;
          break;
        }
      }
    }
    std::cout << faceCount << " faces are incident to vertex 1318\n";

The above code shows that:
![image](https://github.com/pmp-library/pmp-library/assets/1179764/e97394f2-0d77-4d35-b2a7-176f28f4d820)

I checked the original .obj file (also attached), and indeed there are 10 faces incident to vertex 1319 (indices start from 1 in .obj files), so why does the face circulator `mesh.faces(currVert)` only show 2 faces?

[testMesh.zip](https://github.com/pmp-library/pmp-library/files/12694168/testMesh.zip)

**Comment by pbuyssens** [comment]
Hi,

it seems that your mesh contains a lot of duplicates (see image below). 
pmp read_obj function does not seem to deal with duplicates.

![Capture d’écran du 2023-11-21 09-46-48](https://github.com/pmp-library/pmp-library/assets/80264667/6682742c-b971-4d00-97fe-02705cd4bf42)

**Comment by dsieger** [comment]
Such duplicates are indeed a problem. PMP only supports 2-manifold surface meshes and not arbitrary polygon soups. Probably not something we'll change anytime soon.
