### ISSUE TITLE
extract texture png file 

### ISSUE THREAD

**Issue by charleneguillaumot** [pmp-library/pmp-library#178]
Hello, 
I am very new to C++ 
I would be super interested to have the possibility to extract the texture image file that is created after the different parameterization procedures you provide. 
Could you guide me to manage to realise this objective ? 
Many many thanks in advance 
Best regards
Charlène,
University of Burgundy, Dijon, France

**Comment by dsieger** [comment]
There is no image file involved in the parameterization functions we have. We use a simple texture for visualization. This is done in `Renderer::use_checkerboard_texture()`. You could probably adapt this to write the texture data to a file.

Hope this helps
