### ISSUE TITLE
LSCM not a m*n matrix, Why?

### ISSUE THREAD

**Issue by 461353349** [pmp-library/pmp-library#18]
According the paper "Least Squares Conformal Maps for Automatic Texture Atlas Generation", the left Matrix is m*n, m is the face number and n is the vertice number. But the code is n*n matrix. What is the material according to setup the matrix, Can you give me  some clue? Thanks.

**Comment by mbotsch** [comment]
The paper formulates the parameterization problem as the minimization of `norm(A*x-b)`, with an MxN-matrix `A`, an M-vector `b`, and an N-vector `x` (see their equation (4)). This is typically solved through the normal equations, i.e., by solving `transpose(A)*A*x = transpose(A)*b` using a Cholesky decomposition.

Our code directly builds `transpose(A)*A` and `transpose(A)*b`, which are NxN-matrix and an N-vector.

**Comment by 461353349** [comment]
Thanks @mbotsch !
I see.
