### ISSUE TITLE
Valence of faces are unexpectedly 0, affecting is_triangle_mesh()

### ISSUE THREAD

**Issue by eurekesh** [pmp-library/pmp-library#180]
**Describe the bug**
Using suzanne.obj and a variety of other off files (i.e. mario and bunny), I am experimenting with an algorithm that requires a triangular mesh (as well as outputting the end result to an STL, regardless of origin format). I am attempting to detect and triangulate such meshes when encountered, however I have not had much success. I have manually outputted the face valences and it seems that they are all 0s, which would explain why the calls to `is_triangle_mesh()` fail. Any thoughts on how to solve this?

**To Reproduce**
Minimal example
```
SurfaceMesh mesh;
read(mesh, "suzanne.obj"); // or bunny.off, mario.off, etc.
if(!mesh.is_triangle_mesh())
{
   pmp::triangulate(mesh);
}
assert(mesh.is_triangle_mesh()); // fails
```

**Expected behavior**
The mesh should be triangulated, which will allow me to rewrite from n-gon mesh files to STL as an end output and permit my algorithm to be tested.

**Environment (please complete the following information):**
 - OS: Ubuntu 22
 - Compiler: g++ 11.4.0
 - Build type: Release

**Comment by dsieger** [comment]
Can't reproduce this locally (macOS, clang). Added a unit test in ca7ded631 to check on other platforms.

**Comment by dsieger** [comment]
Cross-platform results look OK as well, see https://github.com/pmp-library/pmp-library/actions/runs/6834369309

I'd be really surprised if that function contains an error, it's used all over the place in the library.

Maybe try to reduce your code to a minimum working example and see if it still occurs. Maybe it's just a side-effect of something else you're doing in your code.

**Comment by eurekesh** [comment]
This is a really odd error, running unit tests actually seems to indicate the same behavior! Something I didn't mention before is that this is an ARM Ubuntu release, not sure if that has any bearing.

```Test project /home/ash/Desktop/part_thickness/pmp-library
    Start 1: gtest_runner
1/1 Test #1: gtest_runner .....................Subprocess aborted***Exception:   0.07 sec
terminate called after throwing an instance of 'pmp::InvalidInputException'
  what():  loop_subdivision: Not a triangle mesh.


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.07 sec
```

**Comment by dsieger** [comment]
Which test is failing exactly? You can get more detailed output by running `gtest_runner` directly from the `build/tests` directory.

Ubuntu/ARM could be a factor, don't think we ever tested on that platform.

**Comment by eurekesh** [comment]
CTest attempt:
```
ctest --verbose --output-on-failure
UpdateCTestConfiguration  from :/home/ash/Desktop/pmp-library/build/tests/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/ash/Desktop/pmp-library/build/tests/DartConfiguration.tcl
Test project /home/ash/Desktop/pmp-library/build/tests
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: gtest_runner

1: Test command: /home/ash/Desktop/pmp-library/build/tests/gtest_runner
1: Test timeout computed to be: 10000000
1: terminate called after throwing an instance of 'pmp::InvalidInputException'
1:   what():  loop_subdivision: Not a triangle mesh.
1/1 Test #1: gtest_runner .....................Subprocess aborted***Exception:   0.07 sec
terminate called after throwing an instance of 'pmp::InvalidInputException'
  what():  loop_subdivision: Not a triangle mesh.


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.07 sec

The following tests FAILED:
	  1 - gtest_runner (Subprocess aborted)
Errors while running CTest
```
Manual GTest attempt:
```
ash@ash-QEMU-Virtual-Machine:~/Desktop/pmp-library/build/tests$ ./gtest_runner 
terminate called after throwing an instance of 'pmp::InvalidInputException'
  what():  loop_subdivision: Not a triangle mesh.
Aborted (core dumped)
ash@ash-QEMU-Virtual-Machine:~/Desktop/pmp-library/build/tests$ ./gtest_runner --verbose
terminate called after throwing an instance of 'pmp::InvalidInputException'
  what():  loop_subdivision: Not a triangle mesh.
Aborted (core dumped)
```
I've tried re-pulling PMP, pulling latest version of Eigen, using clang++/g++ - no dice with the triangulation test cases. However, a fresh pull on my M2 Mac (i.e. also ARM) works like a charm. It is a somewhat niche target - I'm going to close this as I don't foresee a fix without an effort to track down some sort of compilation/architecture issue. Thank you for your help!

**Comment by eurekesh** [comment]
As a brief follow-up: after many hours, I determined that the issue affected at the very least all Debian-based ARM distros (via Docker and otherwise) using gcc - using clang++ fixed the issue and allowed the test cases to pass. Also unrelated, but overwriting `INDEX_TYPE` or `SCALAR_TYPE` does cause some test cases to fail (`DecimationTest.simplification` and `DecimationTest.simplification_with_features`). As for the ARM issue, I have no clue why gcc goes off the rails and apparently emits incorrect (!?) machine code. At any rate, case closed!
