### ISSUE TITLE
Regression: Shader info logs are not reported on compile error

### ISSUE THREAD

**Issue by stephan-wenninger** [pmp-library/pmp-library#183]
**Describe the bug**

https://github.com/pmp-library/pmp-library/commit/ca765d31873893737b14fb4e05058ef95bdf565a added the `get_info_log` method in `Shader.h/cpp`, which only queries the `glGetProgramInfoLog` function for reporting the info log back to the user.

This leads to empty info logs, if the shader compilation fails.

**To Reproduce**

Remove for example the GLSL version tags from `PhongShader.h` and run the `./mpview` app. 

Output is only an empty log:
```
Shader: Cannot compile shader:
```

**Expected behavior**
If shader compilation fails, the `glGetShaderInfoLog` function should be called to report the shader info log to the user.

**Additional context**
Noticed this issue, when adding my own (buggy) shader(s) to a project based on pmp.

Best
Stephan

**Comment by dsieger** [comment]
> It seems that shaders that do not compile do not get deleted properly in `cleanup()`, since their `id` is added to `shaders_` only after successful compilation. Probably we should add `id` to `shaders_` after creation, not after compilation, in `compile()` or `load_and_compile()`.

Yep, storing the shader ID directly after creation seems much cleaner. Changed in [09cc75d](https://github.com/pmp-library/pmp-library/commit/09cc75d3da215dbc70436f0b504645e3fc157de4).
