### ISSUE TITLE
SurfaceMesh gives the error result

### ISSUE THREAD

**Issue by lavender-lee** [pmp-library/pmp-library#185]
### Describe the bug
I use Visual Studio to install this library

```
├─bin
│      pmp.dll
│
├─include
│  └─pmp
│      │  bounding_box.h
│      │  ...
│      │  types.h
│      │
│      ├─algorithms
│      │      barycentric_coordinates.h
│      │      ...
│      │      triangulation.h
│      │      utilities.h
│      │
│      ├─io
│      │      helpers.h
│      │      io.h
│      │      io_flags.h
│      │      ...
│      │      write_stl.h
│      │
│      └─visualization
│              cold_warm_texture.h
│              gl.h
│              ...
│              trackball_viewer.h
│              window.h
│
└─lib
    │  pmp.lib
    │  pmp_vis.lib
    │
    └─cmake
        └─pmp
                pmpConfig.cmake
                pmpConfigVersion.cmake
                pmpTargets-release.cmake
                pmpTargets.cmake
```

### To Reproduce

**CMakeLists**

```cmake
cmake_minimum_required(VERSION 3.15)

project(pmp_learn)

# Eigen
set(EIGEN3_INCLUDE_DIR "D:/Win10/cpp-projects/Eigen3/include/eigen3")
include_directories(${EIGEN3_INCLUDE_DIR})

find_package(OpenMP REQUIRED)

# PMP
# https://www.pmp-library.org/installation.html
set(pmp_DIR "D:/Win10/cpp-projects/pmp-library/lib/cmake/pmp")
find_package(pmp REQUIRED)

#
add_executable(hello_world hello_world.cpp)
target_link_libraries(hello_world pmp)
```

**hello_world.cpp**

```cpp
#include <pmp/surface_mesh.h>
 
int main(void)
{
    pmp::SurfaceMesh mesh;
    using pmp::Point;
 
    // add 4 vertices
    const auto v0 = mesh.add_vertex(Point(0, 0, 0));
    const auto v1 = mesh.add_vertex(Point(1, 0, 0));
    const auto v2 = mesh.add_vertex(Point(0, 1, 0));
    const auto v3 = mesh.add_vertex(Point(0, 0, 1));
 
    // add 4 triangular faces
    mesh.add_triangle(v0, v1, v3);
    mesh.add_triangle(v1, v2, v3);
    mesh.add_triangle(v2, v0, v3);
    mesh.add_triangle(v0, v2, v1);
 
    std::cout << "vertices: " << mesh.n_vertices() << std::endl;
    std::cout << "edges: " << mesh.n_edges() << std::endl;
    std::cout << "faces: " << mesh.n_faces() << std::endl;
}
```

which gives
```
vertices: 140727519651236
edges: 1900058488374
faces: 1898375533664
```

### Screenshots

![image](https://github.com/pmp-library/pmp-library/assets/35004095/f01f9854-1e16-44be-864f-c9581ed4c6f8)

### Another trial

```cpp

#include <pmp/surface_mesh.h>
 
int main(void)
{
    pmp::SurfaceMesh mesh;
 
    pmp::read_pmp(mesh, "D:/data/max-planck.obj");

    std::cout << "vertices: " << mesh.n_vertices() << std::endl;
    std::cout << "edges: " << mesh.n_edges() << std::endl;
    std::cout << "faces: " << mesh.n_faces() << std::endl;
   
    return 0;
}
```

![image](https://github.com/pmp-library/pmp-library/assets/35004095/c7eaad6a-ea50-426e-bd86-9369609507c4)

![image](https://github.com/pmp-library/pmp-library/assets/35004095/32c7de99-35fd-400d-ba21-835e898d9687)

Debug within code

```
// resize containers
mesh.vprops_.resize(nv);  // nv 3618422609495269494, unsigned__int64
// _Xlength_error("vector too long");

```
![image](https://github.com/pmp-library/pmp-library/assets/35004095/92331f5f-3876-4509-9853-35d8d7083455)

### Environment 
(please complete the following information):

 - OS: Windows
 - Compiler: Visual Studio 2022
 - Build type: Debug

**Comment by dsieger** [comment]
Sorry, I can't reproduce the issue.

**Comment by githubkusi** [comment]
I can reproduce the very same error in Debug mode. The simple code

    pmp::SurfaceMesh mesh;
    auto numVertices = mesh.n_vertices();

returns something like 140710130840868 (everytime a different value). However, in Release mode, n_vertices() returns the correct value. Using MSVC 2022

**Comment by dsieger** [comment]
This is tested to death in our unit tests, see the `emptyMesh` test in `surface_mesh_test.cpp`. Just ran a dedicated test run on Windows, MSVC 2022 and the test runs fine. See https://github.com/pmp-library/pmp-library/actions/runs/12054948481/job/33614176467

Probably something else in your setup or the particular case you are running. Maybe a missing call to `garbage_collection()`?
