### ISSUE TITLE
OpenGL 4.6 support?

### ISSUE THREAD

**Issue by frnsys** [pmp-library/pmp-library#186]
**Describe the bug**
I'm trying to use `mpview` on Ubuntu 22.04. The program compiles fine but when I run I get the error `Cannot get modern OpenGL context.`. I poked around the code and noticed that `glGetString(GL_VERSION)` returns nothing. I thought maybe this is because I have OpenGL 4.6 installed on my system and not 3.2?

This is the output of `glxinfo | grep "version"`:

```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.1.3
OpenGL core profile shading language version string: 4.60
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.3
OpenGL shading language version string: 4.60
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.1.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, 
```

**To Reproduce**
1. Open '...'
2. Perform '....'
3. See error

**Expected behavior**
`mpview` should launch successfully.

**Screenshots**

**Environment (please complete the following information):**
Ubuntu 22.04, OpenGL 4.6

**Additional context**

**Comment by dsieger** [comment]
Using a newer OpenGL version shouldn't be a problem, this is pretty standard. I would check what the actual OpenGL version reported in https://github.com/pmp-library/pmp-library/blob/e20e5f175216ed04a18b308088e466ebf2b33db4/src/pmp/visualization/window.cpp#L60 is and go from there.

However, this is pretty much all the help I can provide, closing the issue.
