### ISSUE TITLE
In laplace_matrix function, Eigen SparseMatrix setFromTriplets gives "double free or corruption (out)" Error.

### ISSUE THREAD

**Issue by saurabh64sant** [pmp-library/pmp-library#187]
**Describe the bug**
When I run adaptive_remeshing using the following code -
		pmp::adaptive_remeshing(m, 0.001, 0.1, 0.00001, 5, true);

In laplace_matrix function, Eigen SparseMatrix setFromTriplets gives "double free or corruption (out)" Error. The error looks like - 

double free or corruption (out)
Aborted (core dumped)

I know that the error comes from laplace_matrix function during adaptive_remeshing, because I debugged it and found it to come from setFromTriplets call in laplace_remesh function. 

If I use uniform_remeshing the above error does not occur. 

The laplace_matrix function is defined in laplace.cpp file. 

The error occurs in the following code of laplace_matrix of the laplace.cpp file.
----
    // build sparse matrix from triplets
    L.resize(nv, nv);
    L.reserve (triplets.size());
        std::cout << __FUNCTION__ << std::endl;
    L.setFromTriplets(triplets.begin(), triplets.end());
        std::cout << __FUNCTION__ << std::endl;
----

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Compiler: g++ 8.4
 - Build type: Release

**Comment by mbotsch** [comment]
Could you please provide the mesh on which the adaptive remeshing fails?

**Comment by saurabh64sant** [comment]
> Could you please provide the mesh on which the adaptive remeshing fails?
Here is the poly (*.ply) file on which the adaptive remeshing fails. I have changed its extension from *.ply to *.txt.
[cube_outInt.txt](https://github.com/pmp-library/pmp-library/files/13853707/cube_outInt.txt)

As you can see, it is a simple mesh. I use the above mesh for test purpose.

**Comment by dsieger** [comment]
Can't reproduce this either, calling `adaptive_remeshing` with above parameters on the provided example mesh works fine.

Smells like a memory issue somewhere else in your program. Do you get the same error when compiling in `Debug` mode?

**Comment by dsieger** [comment]
Closing due to lack of feedback
