### ISSUE TITLE
Topology Exception reading binary STL files

### ISSUE THREAD

**Issue by delhoume** [pmp-library/pmp-library#190]
I have at least two binary STLs  for Julia fractals that I generate myself using a marching triangle / tetrahedron from a scalar field, then decimating from dozens of gigabytes of raw triangles; and I have this error when loading them into  mpview:
fredericdelhoume@Frederics-Mac-mini 3DFractals % ~/Documents/GitHub/pmp-library/build/mpview bourke_reduced.stl
GLEW   2.2.0
GL     4.1 Metal - 88
GLSL   4.10
highDPI scaling: 2
Multi-sampling uses 4 per pixel
Error: SurfaceMesh::add_face: Complex edge.
libc++abi: terminating due to uncaught exception of type pmp::TopologyException: SurfaceMesh::add_face: Complex edge.
zsh: abort      ~/Documents/GitHub/pmp-library/build/mpview bourke_reduced.stl

I am sure these STLs are clean and do contain mismatched  order triangles, but as they load fine in all software I tried ( meshlab, MacOS preview,   Cura), and the format is not very complicated (to say the least),  so wonder if PMP should fail completely or just ignore these triangles  and give a warning...or at least give the option not no crash.

I would really like to try PMP on them but even this fails.
mconvert -i bourke_reduced.stl -o bourke_reduced_ascii.stl
libc++abi: terminating due to uncaught exception of type pmp::TopologyException: SurfaceMesh::add_face: Complex edge.

So I cannot repair or remove offending triangles in these files using PMP tools, without  modifying code and not throwing TopologyException (or catching at https://github.com/pmp-library/pmp-library/blob/e20e5f175216ed04a18b308088e466ebf2b33db4/src/pmp/io/read_stl.cpp#L134)

Files are quite large (200Mb) so they may be difficult to share (or not) if needed.

Thanks,
<img width="1338" alt="image" src="https://github.com/pmp-library/pmp-library/assets/1763447/2cafc86d-529f-4b7e-bfa4-aa1290a91192">
<img width="1278" alt="image" src="https://github.com/pmp-library/pmp-library/assets/1763447/deb23e8f-320e-460f-952e-ac9356f26466">

**Comment by dsieger** [comment]
Hi Frédéric,

The exception already tells you what's wrong with the mesh you are trying to load: It contains a complex (non-manifold) edge. PMP only supports 2-manifold meshes. The other tools you mention just load an arbitrary triangle soup, not a well-connected mesh. Your best option probably would be to try to fix the non-manifold edges in another tool or to make sure the meshes you generate are 2-manifold.

Hope this helps.

**Comment by delhoume** [comment]
So I guess the best (not the easiest) solution is to fix my mesh generation...
Thanks for answering

**Comment by dsieger** [comment]
Fixing the source of the issue is certainly a good idea.

We might also change the behavior of `add_face()` to ignore such configurations in the future. Keeping this open as a question / reminder.

**Comment by cshan** [comment]
BTW, I have the same issue, is there anyway to fix the "Complex mesh"?

**Comment by delhoume** [comment]
<img width="1025" alt="image" src="https://github.com/pmp-library/pmp-library/assets/1763447/45163459-d944-4e2c-a60d-dd8c28500b61">

<img width="912" alt="image" src="https://github.com/pmp-library/pmp-library/assets/1763447/f6979c90-06ac-4f15-b430-a7197d32d367">

Thank you very much !

**Comment by dsieger** [comment]
Wow, that looks like a lot of non-manifold faces! Run-time must be pretty bad though due to all the exceptions being thrown. However, for the moment that was the minimally invasive change that does not change the API.

Would you mind sharing one of those meshes? Would be a nice case for benchmarking.

**Comment by delhoume** [comment]
Sure.

https://drive.google.com/file/d/1EhtwiregeWaK5MzniIQB_pQRCq0Rrqxg/view?usp=sharing

I have lighter versions of these somewhere but I need to find or regenerate them...

The process is very simple:
-  I use a custom program to generate a huge triangle soup with marching tetrahedra of the fractal scalar field. 
- then I decimate this soup (maybe 30 Gigs) using a very clever out-of-core decimating program hat I only have the Linux executable for (it was given by a student maybe 20 years ago,  can find his name but never hear of him since)
- I then convert to STL the result which can be handled as you can see.

The step where all topology errors are introduced is the polygonization I think, I am not a specialist and my code is very old.
I can share it also if you want.

**Comment by delhoume** [comment]
Update : I found a much smaller file 

https://drive.google.com/file/d/12bQb5UsA3ltwjI027vC1UR7y2LFCw-ev/view?usp=sharing

I also was able to find the decimation program:
```
cluspartred <OPTIONS> filename [filename, ...]
     (c) 2002,2003 by Heiko Lippmann
  OPTIONS:
    -v                                   print version
    -q                                   be quiet (no verbose output)
    -e <double>                          maximum mesh error (> 0.0)
    -p <double>                          mesh inversion penalty (> 1.0)
    -a <double>                          compactness ratio (> 0.0 && <= 1.0)
    -c <integer>                         grid size n for 2^n cells (n >= 1)
    -f <integer>                         grid shift factor (>= 0.6) use with care!
    -t <filename>                        base filename for temporary files
    -r <filename>                        base filename for reduced files
    -i                                   delete input file after processing
    -m                                   delete temporary files after processing
    -s <integer>                         maximum partition size
    -b <xmin xmax ymin ymax zmin zmax>   bounding box
Missing arguments.
Cluspartred version 0.1
```
