### ISSUE TITLE
Incorrect endianness in OFF file handling

### ISSUE THREAD

**Issue by mmuman** [pmp-library/pmp-library#198]
**Describe the bug**
The specification, at least [the one I found](http://www.geomview.org/docs/html/Binary-format.html#Binary-format), dictates the data to be big-endian, but the code here just uses host-endian.

**To Reproduce**
1. run mconvert -b on any .off file
2. hexdump

**Expected behavior**
The data is read and written as big-endian, by default, and attempt is made at reading little-endian data written by previous versions.

**Comment by dsieger** [comment]
Not sure about this one. Seems more like a historical artifact due to the systems of that time being big endian. From the Geomview page:

> This is the native format for 'int's and 'float's on Sun-3's, Sun-4's, and Irises, among others.

I'm not even sure if correct endianness conversion is feasible for floats, see also the Boost.endian [FAQ](https://www.boost.org/doc/libs/1_64_0/libs/endian/doc/index.html#FAQ). Looks like simply swapping bytes around is not sufficient.

**Comment by mmuman** [comment]
Well it's not like big-endian systems completely disappeared anyway, POWER9 can handle both, so using native-endian for a binary on-disk format is really a bad idea.

**Comment by kintel** [comment]
While naive byte swapping may not work well, there are other ways of performing floating point binary I/O, e.g. https://github.com/MalcolmMcLean/ieee754

**Comment by kintel** [comment]
After writing the above I was thinking about how protobuf does binary float encoding, and it looks like they just assume the same endinaness as int32_t and use that to write little endian binaries: https://github.com/protocolbuffers/protobuf/blob/5d876c9fec1a6f2feb0750694f803f89312bffff/src/google/protobuf/wire_format_lite.h#L827

**Comment by dsieger** [comment]
I agree it would be nice to make this consistent with the spec. I'll give it a shot, not sure when I'll find time though.

**Comment by dsieger** [comment]
Our CI is not yet ready for some C++23 functionality I was using to implement this.

**Comment by mmuman** [comment]
Missed this one, thanks! :+1:
