### ISSUE TITLE
How to use the method pick_vertex() in MeshViewer.h?

### ISSUE THREAD

**Issue by XuRongYan** [pmp-library/pmp-library#20]
Hi, 
I want to click somewhere in the mesh viewer and get the vertex I clicked, but I didn't know how to do this after I browed the api reference.
Please tell me if there exists any way to do this.

**Comment by dsieger** [comment]
Hi,

You can find an example for that in the `MeshProcessingViewer::mouse()` function which in turn calls `MeshViewer::pick_vertex()`. Please note, however, that this currently only works with the native C++ version and not when using emscripten.

Hope this helps,
Daniel
