### ISSUE TITLE
`Failed to find wayland-scanner` with newest build under Ubuntu 24.04 LTS (and 20.04) in CLion

### ISSUE THREAD

**Issue by Peasman** [pmp-library/pmp-library#207]
**Describe the bug**
When building the newest [version](https://github.com/pmp-library/pmp-library/commit/e28fdc9d70c843ebd4e3cfc9f42b6a4a77e45ad4) of the pmp-library under Ubuntu 24.04 or 20.04 the cmake configuration fails with 
```
-- Including Wayland support
-- Including X11 support
CMake Error at external/glfw-3.4/src/CMakeLists.txt:76 (message):
  Failed to find wayland-scanner
```
This happens even though I have wayland scanner installed. Perfectly works when configuring with `-DGLFW_BUILD_WAYLAND:BOOL=OFF` 

**To Reproduce**
1. Clone the repository
2. Open it in CLion
3. Build with cmake

**Expected behavior**
Normal configuration and building. 

**Environment (please complete the following information):**
 - Ubuntu 24.04 LTS or Ubuntu 20.04
 - cmake 28.01, gcc 12.0.1
 - CLion 2024.1.3
 - Build type: Debug/Release

**Additional context**
Works when building with VSCode or "by hand" with CMake.

**Comment by dsieger** [comment]
Unfortunately, I don't have a way to reproduce this. Seems to be specific when running CMake from within CLion. Do you have a way to check that `wayland-scanner` is in your `$PATH` when running CLion, e.g., using an integrated terminal or starting CLion from a terminal with correct `$PATH`?

**Comment by seelts** [comment]
same here
running on openSUSE from console (X11)
