### ISSUE TITLE
Can't compile release library with fresh VS2022

### ISSUE THREAD

**Issue by Chernobrovkin-AD** [pmp-library/pmp-library#214]
I tried to compile pmp library into release mode with fresh VS2022 in a usual way:
file->open cmake, and added x64-release configuration.

And building failed with "Internal compiler error":
![image (13)](https://github.com/user-attachments/assets/602e4559-961f-495b-8f77-1798109c771f)

No such issues with debug build, and no such issue with VS2019.

OS Windows 11, VS2022 version - latest for now, 17.11.5.

I managed to compile it with VS2019, so it's not a blocker for me, but it looks like heavy enough to report.

**Comment by dsieger** [comment]
This is an internal compiler error in MSVC while compiling GLFW (`input.c`, `platform.c`), should be reported there. Maybe related to https://github.com/glfw/glfw/issues/2632
