### ISSUE TITLE
I have to manually add each dependancy?

### ISSUE THREAD

**Issue by distractor** [pmp-library/pmp-library#215]
**Describe the bug**
I have a project where I'm already making use of the Eigen library. 

For example, this is a part of my root CMakeLists.txt:

```cmake
# Add Eigen using CPM
CPMAddPackage(
        NAME Eigen
        GITLAB_REPOSITORY libeigen/eigen
        GIT_TAG 3.4.0
        OPTIONS
        "EIGEN_BUILD_DOC OFF"           # Do not build documentation
        "EIGEN_BUILD_PKGCONFIG OFF"     # Optional, disables pkg-config
        "BUILD_TESTING OFF"             # Disable building and running tests
)

# Add PMP library using CPM
# Set EIGEN3_INCLUDE_DIR if it is not already defined
if (NOT DEFINED EIGEN3_INCLUDE_DIR)
  set(EIGEN3_INCLUDE_DIR "${Eigen_SOURCE_DIR}/")
endif()
find_package(Eigen 3.4.0 REQUIRED)
CPMAddPackage(
        NAME PMP
        GITHUB_REPOSITORY pmp-library/pmp-library
        GIT_TAG 3.0.0  # Specify the version you need, or leave it out for the latest
        OPTIONS
        "PMP_BUILD_TESTS OFF"      # Prevents building tests
        "PMP_BUILD_EXAMPLES OFF"   # Prevents building examples
        "PMP_BUILD_DOCS OFF"       # Prevents building documentation
)
```

This makes the PMP use my instance of Eigen which is all fine and well. But after trying to compile, I get an error:

```bash
CMake Error at cmake-build-debug/_deps/pmp-src/external/glfw-3.3.8/src/CMakeLists.txt:91 (add_library):
  Cannot find source file:

    external/glfw-3.3.8/include/GLFW/glfw3.h
```

Which makes me think that I will have to manually install **all** PMP dependencies. That for sure is not something I want to do.

**Expected behavior**
Don't ask the user to install **all** dependencies?

**Environment (please complete the following information):**
 - OS:  Linux 24.04
 - Compiler: gcc
 - Build type: Debug

**Comment by dsieger** [comment]
By default, we build the OpenGL viewers and apps which depend on glfw. You can disable that through the `PMP_BUILD_VIS` option.
