### ISSUE TITLE
I found that in the triangulation function, it checks the legality of a point.  It seems to me that this might not be necessary.

### ISSUE THREAD

**Issue by jellychen** [pmp-library/pmp-library#217]
if (!mesh_.is_manifold(mesh_.to_vertex(h)))
       {
            auto what = std::string{__func__} + ": Non-manifold polygon";
            throw InvalidInputException(what);
        }

What considerations are there for checking the legality of a point here? It seems unnecessary. Or have I missed something?

**Comment by dsieger** [comment]
The algorithm only works on manifold faces, as documented in the pre-condition of `triangulate(SurfaceMesh&, Face)` in `triangulation.h`. This checks for the pre-condition.
