### ISSUE TITLE
What is the rationale and purpose of this code?

### ISSUE THREAD

**Issue by DWR-CMQ** [pmp-library/pmp-library#219]
Hi,the cholesky_solve function in pmp\algorithms\numerics.cpp,I do not know why,Can you tell me the rationale and purpose of this code?
![image](https://github.com/user-attachments/assets/d25663a5-65e5-4870-81ce-3913a8775a7c)

**Comment by mbotsch** [comment]
This code moves the "known unknowns" to the right-hand side. It builds a new matrix AA and right-hand side BB, such that only the true unknowns remain and all constrained degrees of freedom are on the right-hand side.
