### ISSUE TITLE
Geodesic path between two mesh points

### ISSUE THREAD

**Issue by lukkio88** [pmp-library/pmp-library#31]
Hi,

Given a mesh and two points represented as triples `(triangleId,baricentricCoord1,baricentricCoord2)`, is it possible to compute the "geodesic path" (represented somehow) between such vertices on the mesh?

I can see you have a function for "geodesic distance" but I'm not sure about the path.

**Comment by dsieger** [comment]
Hi,

Sorry, we currently don't have such functionality, I guess you are on your own for this one.

Thanks,
Daniel
