### ISSUE TITLE
Non-manifold meshes

### ISSUE THREAD

**Issue by j8asic** [pmp-library/pmp-library#33]
I'm trying to deal with non-manifold meshes, and for example I'd like to separate non-manifold mesh into manifold parts via the flood fill algorithm. Flooding stops when edge has != 2 adjacent faces. But I see no `FaceAroundEdgeCirculator`, `is_nonmanifold(Edge)` and similar functions which I think would be nice to have. How does one find all neighbour faces over face's (half)edge with current functionality?

**Comment by dsieger** [comment]
Hi,

We are currently not supporting non-manifold meshes. We have some ideas for adding some support in the future, but I'm not sure when or if we'll find time to work on this. Marking this as enhancement request.

Daniel

**Comment by j8asic** [comment]
Hi Daniel, thanks for the reply. For the moment, users can input separate manifold parts of the nonmanifold mesh to be remeshed, while locking connection edges... so it's not a big of a deal.

**Comment by dsieger** [comment]
Ain't gonna happen in the foreseeable future.
