### ISSUE TITLE
Locking vertices and edges instead/in addition to the selection

### ISSUE THREAD

**Issue by j8asic** [pmp-library/pmp-library#34]
In function `SurfaceRemeshing::preprocessing()`, locked property is forcefully added as follows:
```
    vlocked_ = mesh_.add_vertex_property<bool>("v:locked", false);
    elocked_ = mesh_.add_edge_property<bool>("e:locked", false);
```
It would be convenient if the property is added only if it doesn't exist, so that users themselves can lock vertices and edges, instead of selecting remeshable vertices. So this locked property may be used later for future mesh manipulations, not only for remeshing. Something like:
```
    vlocked_ = mesh_.vertex_property<bool>("v:locked", false);
    elocked_ = mesh_.edge_property<bool>("e:locked", false);
```
And locked property should not get deleted in postprocessing functions. Also, "locked" would have greater priority than "selected".

Just a suggestion... Don't know if it makes sense... I agree that users can manipulate selections before an operation.

**Comment by dsieger** [comment]
Hi,

Thanks for your suggestion. I am hesitating a bit though. It seems this would be an alternative way to achieve the same result as currently possible through the selection property. For sake of simplicity, we generally prefer to have a single way to achieve a certain result.

However, I do agree that our "implicit" usage of internal properties is not optimal, and we might change this in a future release.

Thanks,
Daniel

**Comment by dsieger** [comment]
Re-visiting this issue: We'll keep things simple and consistent: Using selections is the way to restrict the application of an algorithm. It's already used in several places. Introducing another way to achieve the same result would lead to additional maintenance burden and potential issues (prioritization of selection vs locking).

Thanks,
Daniel
