### ISSUE TITLE
Edge is locked by its single vertex instead of both its vertices

### ISSUE THREAD

**Issue by j8asic** [pmp-library/pmp-library#35]
Sometimes a single edge or polyline needs to be preserved when remeshing, but this should not include vertices adjacent to the edge or polyline.

So formally, there should be the and `&&` operator instead of the or `||` operator, when checking if an edge should be locked based on its vertices:
[https://github.com/pmp-library/pmp-library/blob/master/src/pmp/algorithms/SurfaceRemeshing.cpp#L134](url)

Sorry to annoy with issues, this is my last one :)

**Comment by dsieger** [comment]
Hi,

Thanks for your feedback, we are looking into it.

Daniel

**Comment by dsieger** [comment]
Sorry for the long delay, we discussed this issue back and forth one or two times :smile: 

In short, you could argue both ways in case of selected vertices. The current implementation intentionally chose the `||` operator, and we think it is the better choice as it leads to better results in the transition region. Here is one example:

![remesh_selection_comparison](https://user-images.githubusercontent.com/6951585/121091236-fb28e200-c7e9-11eb-8c78-5aa31dd9f368.jpg)

**Comment by j8asic** [comment]
Thanks for this feedback, and I understand.
I introduced the issuse due to the need of preserving specific edges. Can we at least have control whether to use "and" or "or", or another option for inputting a set of preserved edges?

**Comment by dsieger** [comment]
Just using feature edges is not enough?
