### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by hwkim0325** [pmp-library/pmp-library#36]
**To Reproduce**
I tried to use this library in VS2015 x64
However, when I build on a cmake application,
I saw these errors.
As I went to the external folder, some of the folder's contents are not exist.
How can I compile this? I want to use this library on a window 10!.

**Expected behavior**
generate sln file in a correct way.

**Screenshots**
![image](https://user-images.githubusercontent.com/40055222/90019009-c7c01880-dce8-11ea-8b3f-bf4145459095.png)
![image](https://user-images.githubusercontent.com/40055222/90019022-cd1d6300-dce8-11ea-8370-bd2f7a0393ff.png)
![image](https://user-images.githubusercontent.com/40055222/90019048-d7d7f800-dce8-11ea-81c6-d1200abc0868.png)
![image](https://user-images.githubusercontent.com/40055222/90019055-dd354280-dce8-11ea-980a-723665c1d143.png)
![image](https://user-images.githubusercontent.com/40055222/90019076-e1616000-dce8-11ea-9111-fc32d11fbe37.png)
![image](https://user-images.githubusercontent.com/40055222/90019088-e7574100-dce8-11ea-9df6-42f14083d6e0.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Compiler: c++ (VS 2015 x64)
 - Build type: Debug

**Additional context**

**Comment by hwkim0325** [comment]
![image](https://user-images.githubusercontent.com/40055222/90024637-0c9b7d80-dcf0-11ea-8f0d-799344df8a05.png)
![image](https://user-images.githubusercontent.com/40055222/90024650-11f8c800-dcf0-11ea-9cf5-f650a78e382f.png)
![image](https://user-images.githubusercontent.com/40055222/90024664-17eea900-dcf0-11ea-84e3-824d424ae77f.png)
![image](https://user-images.githubusercontent.com/40055222/90024673-1c1ac680-dcf0-11ea-862b-59d519704f27.png)
I download these separately and build the sln file.
However, When I load the library, I got this error.
![image](https://user-images.githubusercontent.com/40055222/90024929-6b60f700-dcf0-11ea-825b-5c65bdcf93b2.png)
![image](https://user-images.githubusercontent.com/40055222/90024941-7025ab00-dcf0-11ea-967f-b17b6c8044d7.png)

**Comment by hwkim0325** [comment]
OK, I make the Eigen files independently, and work fine, Thank you.

**Comment by dsieger** [comment]
Please remember to clone the repository recursively so that external dependencies are fetched correctly:

```bash
git clone --recursive https://github.com/pmp-library/pmp-library.git
```

Thanks,
Daniel
