### ISSUE TITLE
Circulator compatibility with STL

### ISSUE THREAD

**Issue by timo-oster** [pmp-library/pmp-library#42]
Hi and thanks for this library. I like the interface a lot. 

It seems like you strive to be compatible with the STL as much as possible, but I noticed that your circulators do not specialize std::iterator_traits. This is a shame, because it prevents me from using some STL algorithms or functions that are usually possible with pairs of iterators. For example, if I wanted to add all vertices of a vertex circulator to a container, I would call `container.insert(container.end(), mesh.vertices(v).begin(), mesh.vertices(v).end())`. This fails to compile with gcc, because it requires std::iterator_traits to be specialized (or the relevant typedefs to be directly included into the circulator type). Is there a specific reason why this can't be implemented? Are the circulators incompatible with the STL's LegacyIterator concepts? Or has it simply not been implemented yet? Some STL algorithms that theoretically require these concepts to be implemented seem to work fine, so maybe it just hasn't come up yet.

Best,

Timo

**Comment by dsieger** [comment]
Hi Timo,

Glad you like our library, hope it'll be useful.

Regarding STL compatibility: We simply did not need it so far, so we never looked into it. However, we had a similar request in the past, and the functionality seems useful, so this might be something to add in the future. It probably won't end up very high on my priority list, though. Patches/PRs are welcome!

Thanks,
Daniel
