### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by chongjeelee** [pmp-library/pmp-library#43]
I use pmp library in win10,but when i configure it ,it occured CMake Error at CMakeLists.txt:54(add_subdirectorty):The source directory  ../pmp-library-master/external/glfw does not contain a CMakeLists.txt file.
pls help me to solve it ,thank you very much.

**Comment by dsieger** [comment]
Please make sure that you cloned the repository recursively so that the required dependencies get fetched:

```
git clone --recursive https://github.com/pmp-library/pmp-library.git
```

**Comment by chongjeelee** [comment]
Thank you so much, i will try it.



lzjnlkd@163.com
 
From: Daniel Sieger
Date: 2020-10-27 19:35
To: pmp-library/pmp-library
CC: chongjeelee; Author
Subject: Re: [pmp-library/pmp-library] CMake error (#43)
Please make sure that you cloned the repository recursively so that the required dependencies get fetched:
git clone --recursive https://github.com/pmp-library/pmp-library.git

**Comment by chongjeelee** [comment]
hi,and now ,cmake all right,but when i run .sln in VS2015,it occured error LNK110:not find ..\debug\pmp.lib
i search on web ,this bug maybe generated by path ,but i don't know to refine it .
