### ISSUE TITLE
run error in VS2015

### ISSUE THREAD

**Issue by chongjeelee** [pmp-library/pmp-library#44]
![图片](https://user-images.githubusercontent.com/30140969/97384644-13a75480-190b-11eb-91b7-8c37fa4578db.png)

i generated in cmake successfully ,but occured error when i used in vs2015 win10.
please give me help ,thank you.

**Comment by dsieger** [comment]
Sorry, this works fine both on my local machine as well as our build servers. I'm afraid we can't offer support beyond that.
