### ISSUE TITLE
Support for general properties in pmp format

### ISSUE THREAD

**Issue by thovide** [pmp-library/pmp-library#49]
Hello,

the pmp format stores and restores texture properties on half-edges. Shouldn't it use properties on vertices (they are stored in vertex properties in SurfaceGeodesic and SurfaceCurvature), 

Thanks

BTW, I love your library!

**Comment by dsieger** [comment]
Hi,

Thanks for the feedback, glad you like our library.

To your question: The raw `.pmp` format is currently very limited. I hacked this together to have a quick and dirty binary save/restore for some specific application. We basically have no proper way to handle arbitrary properties in the format. I had this on my list as well. Marking this as enhancement.

Thanks,
Daniel

**Comment by thovide** [comment]
Thanks Daniel,

actually i was interested in this format because of its efficiency for the mesh reconstruction. I don't use the format myself but duplicated the logic to integrate it in my own stream and saw that texture property management looked weird. 

BTW, it forces me to add my class as a friend class of SurfaceMesh in order to access properties resizing. I'd prefer avoiding this so that I don't have to modify your classes later if I switch to another version of pmp.

Another question : do you plan to include dllexport mechanism in your library? I'd like to keep your code isolated in a standalone library and I've currently to add explicit symbol export code in your classes

**Comment by dsieger** [comment]
I see. A more general serialization mechanism to read/write from/to arbitrary streams would definitely be nice to have.

Regarding dllexport: We did not have a real use case for that so far, so I did not bother. What's your concern with simply using the static library?

**Comment by thovide** [comment]
In my case, I'm requested to split Open Source code and ours. I must use a dll. 

Not a big deal, I just added export symbols to the classes I use.

**Comment by dsieger** [comment]
Fair enough, I opened #51 to track the dllexport.

I'll rename this one to be about support for general properties in the pmp format.

I'll eventually add another one about supporting serialization to/from a stream.

Thanks again for your feedback!

**Comment by dsieger** [comment]
Ain't gonna happen in the foreseeable future.
