### ISSUE TITLE
Add dllexport mechanism to allow dll usage

### ISSUE THREAD

**Issue by dsieger** [pmp-library/pmp-library#51]
We currently only support static libs on Windows. Adding a dllexport mechanism would allow users to use shared libs as well, which might be necessary due to legal or other project requirements.

**Comment by petrasvestartas** [comment]
Is it difficult to add a dynamic library support? I would like to use for my research in CAD environment for PInvoke with .NET libraries. But for this I need to know how to compile PMP to .dll. While the PInvoke I can do myself.

Is it possible to do this any time soon?

**Comment by petrasvestartas** [comment]
Anyone?

**Comment by dsieger** [comment]
I'm looking into this. The thing is: I'd like to avoid the classic approach of sprinkling dllexport macros all over the code. There is some support in newer CMake versions to automatically export the symbols. This seems to work, but I have not tested it beyond compiling our code. I also need to implement a solution for our test runner to find the dlls.

I pushed my current state to the `dllexport` branch, maybe that's already good enough to get you started.

**Comment by petrasvestartas** [comment]
Thank you for the reply 

Is it enough to write two lines in windows bash/terminal from repo of dllexport?


git clone --recursive https://github.com/pmp-library/pmp-library.git

cd pmp-library && mkdir build && cd build && cmake .. && make


Do I need to download additional libraries or specially configure cmake?

**Comment by dsieger** [comment]
You'll need to switch to the `dllexport` branch after checkout:

```sh
git checkout dllexport
```

The build command probably is not `make` on Windows. You could use something like

```
cmake --build .
```

No additional libraries required, shared libraries are enabled by default. This might become a CMake option before merging to master.

**Comment by petrasvestartas** [comment]
Thank you for the help, but I need a step-by-step guide for me, as I am beginner.
This is what I checked so far:

git checkout dllexport produces an error and does not switch to dll export branch:
![Bash](https://user-images.githubusercontent.com/18013985/126859631-7f33371e-0f22-408b-92f3-8fd92130f24a.png)

I also tried just to download dllexport manually from github and in this case CMake gives error, after I press configure and choose compiler, also references not found from Clang:
![Export](https://user-images.githubusercontent.com/18013985/126859700-7bddab65-dfa0-45f9-a86c-1543afb6cec9.png)

**Comment by petrasvestartas** [comment]
I also did this: 
```
$ git clone --single-branch --branch dllexport --recursive https://github.com/pmp-library/pmp-library.git
cd pmp-library && mkdir build && cd build && cmake .. && make

```

After which I have following:
![Make](https://user-images.githubusercontent.com/18013985/126860220-786dbd06-1c16-4944-b76b-0d3a6cd6c81b.png)

And some files after Visual Studio building:
![image](https://user-images.githubusercontent.com/18013985/126860231-eaa6b523-c3cb-4d5e-91c1-a78a09ae4084.png)

Is this correct what I am doing?

**Comment by dsieger** [comment]
> And after opening "pmp-library.sln" in Visual Studio and building all projects, I see some .dll files :

That looks OK.
 
> Does it mean that in Bash I can directly write this to build projects even without Visual Studio:

Yes, `cmake --build` will invoke MSBuild to build the solution.

> What minimal example shall I test to minimally know that I can load a file (without UI) ?

You can pick any of the examples from the `examples` directory. They only link against the core library containing the data structure and algorithms, no UI involved. You can build the examples by configuring CMake with

```sh
cmake -DWITH_EXAMPLES=ON ..
```

**Comment by petrasvestartas** [comment]
Sorry, I am not very familiar with CMake, should I modify this file:
https://github.com/pmp-library/pmp-library/blob/dllexport/CMakeLists.txt

If yes, which line?

Or I should add this line
`cmake -DWITH_EXAMPLES=ON ..`
To this:
```
cd pmp-library && mkdir build && cd build && cmake --build .
instead of:
```

**Comment by dsieger** [comment]
```sh
cd pmp-library && mkdir build && cd build && cmake -DWITH_EXAMPLES=ON .. && cmake --build .
```
should do the trick. However, I'd suggest to get more familiar with CMake. This type of question / support usually is beyond the scope of our project.

**Comment by dsieger** [comment]
Merged into master, closing.

**Comment by petrasvestartas** [comment]
Yay... Thank you very much for all your patience. It runs:

![image](https://user-images.githubusercontent.com/18013985/126881584-348cbe9e-3f52-4f35-b332-07564cb760b6.png)
