### ISSUE TITLE
How to use libpmp library on javascript?

### ISSUE THREAD

**Issue by brupelo** [pmp-library/pmp-library#54]
Hi, I'd like to give it a shot to pmp-library with javascript, I've just followed the docs that says:

> mkdir jsbuild
> cd jsbuild
> emconfigure cmake ..
> make

and as a result I've got this:

```
>ls
CMakeCache.txt           curview.wasm     libimgui.a      mview.wasm             smoothing.html
CMakeFiles               decimation.data  libpmp.a        parameterization.data  smoothing.js
CPackConfig.cmake        decimation.html  libpmp_vis.a    parameterization.html  smoothing.wasm
CPackSourceConfig.cmake  decimation.js    libstb_image.a  parameterization.js    src
build.ninja              decimation.wasm  mpview.data     parameterization.wasm  subdiv.data
cmake_install.cmake      external         mpview.html     remeshing.data         subdiv.html
cmake_uninstall.cmake    fairing.data     mpview.js       remeshing.html         subdiv.js
curview.data             fairing.html     mpview.wasm     remeshing.js           subdiv.wasm
curview.html             fairing.js       mview.html      remeshing.wasm
curview.js               fairing.wasm     mview.js        smoothing.data
```

This is the first time I'm using emscripten so I'm a little bit lost... but I understand I should get a wasm file of libpmp, isn't? Could you please explain how to use just the library on javascript?

**Comment by mbotsch** [comment]
We only cross-compile our example apps to wasm (all the html files), but not the library itself. I never tried the latter and therefore cannot help  with setting up a Javascript app that accesses the wasm-based pmp-library.

To use the wasm apps, you can open them with `emrun <appname>.html`. Or start a local webserver in the build directory (e.g. using `python3 -m http.server`) and then open the html files in your browser from `localhost:8000`.

**Comment by dsieger** [comment]
As Mario mentioned, we are currently not building a standalone .wasm file of the library. However, here are some pointers that might help:

It looks like this [question](https://stackoverflow.com/questions/63622009/static-library-built-with-cmake-as-a-with-emscripten-instead-of-wasm-js) on StackOverflow covers your use case. It basically boils down to creating a separate executable target in CMake. This [gist](https://gist.github.com/WesThorburn/00c47b267a0e8c8431e06b14997778e4) also covers the CMake setup.

There also seems to be [some way](https://www.dynamsoft.com/codepool/webassembly-standalone-dynamic-linking-wasm.html) to support dynamic linking, but I don't think CMake currently supports any of this.

Sorry for not having a more comprehensive answer to your request, but this is probably all the support we can offer for now.

Thanks,
Daniel

**Comment by brupelo** [comment]
Hey guys, ok, thanks nevertheless, if I ever find the time I'll give it another shot, I was just waiting to see if you ever tried this one. And yeah, I know those html "exes" will run out of the box flawlessly using any web server. In this case I was interested about the library itself as I'd like to use it along three.js and make some mesh processing.

@dsieger Daniel, thanks for those links, I'll carefully take a look when I allocate some time... one question, why did you decide to close this one? Is it because your answer is providing already the solution or is it because my question is offtopic?

In any case, thanks... using the library as "standalone" in js land would be pretty amazing to make some serious mesh processing ;)

**Comment by dsieger** [comment]
@brupelo I closed the issue because it is very unlikely that either Mario or me will look into this further at this point. Your question is not off topic, it's just not something that we support at the moment.
