### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by m-bob** [pmp-library/pmp-library#58]
# Description

Can you provide help on compiling/linking an example program? I'm trying to get SurfaceMeshBasics.cpp to compile and run on my Mac running OS 10.15.7 . 

My first attempt failed because it couldn't find the Eigen/Dense header. I believe I fixed that. My second attempt failed because it couldn't understand constantexp (or something like that). I added the -std=c++11 flag, which seems to have fixed that.

My third attempt is to try to execute cc SurfaceMeshBasics.cpp -std=c++11 -lpmp -o test which now fails because of linker errors (undefined symbols).

I now get ...

cc SurfaceMeshBasics.cpp -std=c++11 -lpmp -o test
Undefined symbols for architecture x86_64:
  "std::__1::locale::use_facet(std::__1::locale::id&) const", referenced from:
      std::__1::ctype<char> const& std::__1::use_facet<std::__1::ctype<char> >(std::__1::locale const&) in SurfaceMeshBasics-4124ec.o
  "std::__1::ios_base::getloc() const", referenced from:
      std::__1::basic_ios<char, std::__1::char_traits<char> >::widen(char) const in SurfaceMeshBasics-4124ec.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(unsigned long, char)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(unsigned long, char) in SurfaceMeshBasics-4124ec.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in SurfaceMeshBasics-4124ec.o
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::put(char)", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::endl<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) in SurfaceMeshBasics-4124ec.o
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::flush()", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::endl<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) in SurfaceMeshBasics-4124ec.o 

...

It looks to me like the linker is finding the pmp library, but that the library is not what it's expecting. I followed the instructions I found for building and installing the library.

My knowledge of and experience with C++ are obviously limited. But I have a reasonable expectation of accomplishing what I want to -- provided I can get past this step.

(Incidentally, have you considered providing Python bindings?)

Thanks for your help!

Murray

## How to Reproduce

Described above.

## Expected behavior

An executable which, when run, prints the expected output.

## Actual behavior

Link fails.

## Reproducibility

100%

**Comment by dsieger** [comment]
Hi,

Compiling and running the examples should be straightforward:

1. Fetch the repository:

```sh
# don't forget the --recursive flag to get external libraries
git clone --recursive https://github.com/pmp-library/pmp-library.git
```

2. Create the build directory:

```sh
cd pmp-library && mkdir build && cd build
```

3. Run CMake

```sh
cmake -DWITH_EXAMPLES=True ..
```

4. Build
```sh
make -j
```

5. Run the example
```sh
$ ./SurfaceMeshBasics 
vertices: 4
edges: 6
faces: 4
```

That should be enough to get you started. Also have a look at the [template project](https://github.com/pmp-library/pmp-template) and the [quickstart guide](http://www.pmp-library.org/quickstart.html).

If you insist on compiling by hand (i.e., manually invoking your compiler of choice instead of using CMake) you are basically on your own. However, it looks like you are invoking the C compiler `cc` instead of the C++ compiler `c++` (or `g++` or `clang++` or similar). Changing to a C++ compiler should get rid of the errors you described.

Regarding Python bindings: We did consider adding them but decided against it for the moment. We try to keep things simple, and we try not to add bells and whistles we don't actually use.

Hope this helps,
Daniel

**Comment by m-bob** [comment]
Hi Daniel, 

Thank you!

Thank you for replying so quickly and for the detailed information.

I'll have to learn how to use CMake. (I've run canned examples before, but never tried to make my own CMake file.)

But I don't have to do that immediately. Your other suggestion worked too.

Typing  clang++ SurfaceMeshBasics.cpp -std=c++11 -lpmp -o test produces a test executable which behaves as expected.

(In case anyone else is interested, for my current configuration I need to use clang++ and I also need to set the -std=c++11 flag.)

Again, thank you so much!

Murray

**Comment by dsieger** [comment]
You're welcome
