### ISSUE TITLE
volumes

### ISSUE THREAD

**Issue by filiatra** [pmp-library/pmp-library#6]
Hi there,

The pmp-library project looks very interesting. I like the way you build the inheritance bottom up. In fact it seems that it can be easily extended to volumes (i.e. VolumeMesh, inherited from SurfaceMesh).

Is something like that planned? or would you be interested in it ?

best
Angelos

**Comment by dsieger** [comment]
Hi Angelos,

We thought a bit about adding support for volume meshes. A simple data structure surely could be added without too much effort. However, implementing a data structure that *properly* generalizes from surfaces to volumes and also supports topological changes is not completely straightforward. Although this would be an interesting addition to the library, we have not planned anything like that for the moment.

Keeping the issue open as enhancement request.

Thanks,
Daniel

**Comment by dsieger** [comment]
We decided to get rid of the inheritance hierarchy, so no volume meshes in the foreseeable future.
