### ISSUE TITLE
Fitting a NURB surface to a mesh

### ISSUE THREAD

**Issue by ted944** [pmp-library/pmp-library#60]
Not sure if this is requested before. 

We get asked about this a lot to convert a mesh generated from a volumetric image like CT to a NURB surface that can be imported to a 3D CAD package like Solidworks for modeling use. A STL file of triangle mesh can be problematic when the number of faces is huge.

It would be a powerful function to have. 

Thanks

Ted

**Comment by dsieger** [comment]
Indeed, this would be an interesting functionality to have. However, we currently do not intent to add something like this.
