### ISSUE TITLE
How to effectively use the mesh smoothing function?

### ISSUE THREAD

**Issue by ted944** [pmp-library/pmp-library#61]
Hi,

I'm trying to use the "SurfaceSmoothing" class to smooth a surface mesh generated using MarchingCube algorithm. 

I used the "ExplicitSmoothing" with the default parameters, but somehow I don't see any smoothing effect. The surface looks like before, with all the voxel edges etc. I'd like to get a smoother surface for the mesh.

This example is a portion of the mesh after 10 iterations of smoothing:

![image](https://user-images.githubusercontent.com/6178845/106282316-6c3e0480-620e-11eb-8077-b24270fdb689.png)

I'd like to get some feedback, if I'm using the right class and what values to use for the parameters.

Thanks for the great library you have developed, keep up the good work!

Ted

**Comment by dsieger** [comment]
Please try to increase the number of iterations if you need more smoothing.

**Comment by dsieger** [comment]
Closing due to lack of feedback
