### ISSUE TITLE
Fill hole results in extremely large mesh

### ISSUE THREAD

**Issue by cdcseacave** [pmp-library/pmp-library#67]
I was playing around with hole filling functionality, and I found many cases in which the refine part of the algorithm increases the size of the mesh with millions of new vertices and faces. Please find attached an example mesh with 8 vertices, for which calling `fill_hole(pmp::Halfedge(3));` adds ~32million new vertices and faces.

[holeMesh.zip](https://github.com/pmp-library/pmp-library/files/6452407/holeMesh.zip)

**Comment by dsieger** [comment]
Looks like the .zip file just contains an empty directory. Could you check?

**Comment by cdcseacave** [comment]
after more digging it looks like it is related to this issue #64, I'll test...

**Comment by dsieger** [comment]
Got the mesh, works fine for me on latest master
