### ISSUE TITLE
Conan support

### ISSUE THREAD

**Issue by sunbubble** [pmp-library/pmp-library#68]
Would it be possible to add Conan support to pmp?

It would make it much easier to integrate the library into projects that already share dependencies with pmp. As Conan does version resolution. We add some issues trying out pmp, because of different Eigen versions.
Conan would be fairly unobtrusive, and be triggered on the cmake configuration step. So it shouldn't increase the barrier of adoption for new pmp users. Hopefully rather the opposite. Context: https://github.com/pmp-library/pmp-library/issues/13  

Thanks in advance

**Comment by sunbubble** [comment]
I also had a quick look and 5/8 dependencies are already available on Conan centre. The exceptions are obviously `pmp-data`, `rply` and `stb_image`.

**Comment by dsieger** [comment]
Hi,

Thanks for your suggestion. However, I'm afraid I the answer is "no" for the moment. I'm not looking forward to integrate, test, maintain, and support another installation workflow. Unfortunately, the C++ package management landscape is so fragmented that I don't really see a good path forward here. Right now we don't even properly support using anything else than the bundled libraries (i.e., no FindPackage support). To me, this would be a prerequisite before even thinking about any package manager.

Thanks,
Daniel

**Comment by sunbubble** [comment]
That's unfortunate. Thanks for the reply in any case.
