### ISSUE TITLE
Add support to view multi meshes one time

### ISSUE THREAD

**Issue by grassofsky** [pmp-library/pmp-library#71]
**Describe the solution you'd like**
- Support to load and view multi-meshes

**Additional context**
- With this feature, can test operation between multi-meshes

**Comment by dsieger** [comment]
Hi @grassofsky 

Adding support to view and process multiple meshes at the same time certainly would be a useful feature. However, this would require substantial changes to our viewer and rendering code. Unfortunately, I don't see this happening anytime soon. Therefore I'm closing the issue for now.
