### ISSUE TITLE
arch:SSE warnings when building on Windows

### ISSUE THREAD

**Issue by kjez** [pmp-library/pmp-library#72]
Hello!

When building on x64 windows, like here: https://github.com/pmp-library/pmp-library/runs/2933831928?check_suite_focus=true
there are warnings about the SSE compiler flag used on MSVC:
cl : command line warning D9002: ignoring unknown option '/arch:SSE'

https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-160 shows that this is not a valid option for x64 builds and that SSE2 is used by default when no option is specified.

Thanks

**Comment by dsieger** [comment]
Thanks for spotting this one!
