### ISSUE TITLE
Subdivision detect_boundary does not work

### ISSUE THREAD

**Issue by petrasvestartas** [pmp-library/pmp-library#75]
Subdivision 

**Describe the solution you'd like**
Boundary edges have to stay in their original position

**Additional context**
Code with boundary detect that does not work:

```
void Subdivide(SurfaceMesh& PMPmesh, int n = 1, int type = 0, double detectAngle = -1, int detectBoundaries = 0) {


	//Angle contraint
	SurfaceFeatures(PMPmesh).clear();
	SurfaceFeatures sf(PMPmesh);
	if (detectAngle > 0) {
		sf.detect_angle(25);
	}

        //This does not work
	if (detectBoundaries > 0) {
		SurfaceFeatures sf(PMPmesh);
		sf.detect_boundary();
	}

	//Subdivide into different types
	for (int i = 0; i < n; i++) {
		if(type == 0) SurfaceSubdivision(PMPmesh).catmull_clark();
		else if (type == 1) SurfaceSubdivision(PMPmesh).loop();
		else if (type == 2) SurfaceSubdivision(PMPmesh).sqrt3();
	}


	//Compute normals
	SurfaceNormals::compute_vertex_normals(PMPmesh);
	SurfaceNormals::compute_face_normals(PMPmesh);


}
```

[mesh.zip](https://github.com/pmp-library/pmp-library/files/6909959/mesh.zip)
![Boundary](https://user-images.githubusercontent.com/18013985/127710314-0a2fade8-8776-4c1d-b24e-29f309cf7fb9.png)

**Comment by mbotsch** [comment]
This is the intended behavior for subdivision surfaces with boundary. The boundary will also be subdivided, but using a particular univariate subdivision rule.
