### ISSUE TITLE
Curvature 1D texture result not in range of  [0;1]

### ISSUE THREAD

**Issue by petrasvestartas** [pmp-library/pmp-library#76]
Hi,

I am trying to print mean gaussian values in 1D texture, but the values are not in range [0,1]. Is this a normal behavior? E.g. third line is 1.24724.

I am trying to get the same vertex coloring as in your readme file/web ui using red, white and blue colors. And I do not understand how curvature values are distributed. Is x<0.5 negative curvature and x>0.5 positive?

I attach the printed results, also colors seems to be off  using `PMPmesh.vertex_property<TexCoord>("v:tex");`:
```
Value 0.563799
Value 0.416455
Value 1.24724
Value 0.87067
Value 0.368681
Value 0.23511
Value 0.607101
Value 0.827764
Value 0.415169
```

These are all the printed values:
[PMPCurvature.txt](https://github.com/pmp-library/pmp-library/files/6911837/PMPCurvature.txt)

And this is the screenshot of the bunny:
![image](https://user-images.githubusercontent.com/18013985/127764499-48bfa67d-6ce1-4811-9b68-c426f5edecac.png)
[bunnyHigh.zip](https://github.com/pmp-library/pmp-library/files/6911838/bunnyHigh.zip)

This is the source code
```
inline VertexProperty<TexCoord> Curvature(SurfaceMesh& PMPmesh, int type = 0) {

	//Compute normals
	SurfaceNormals::compute_vertex_normals(PMPmesh);
	SurfaceNormals::compute_face_normals(PMPmesh);

	//Compute curvature
	SurfaceCurvature* curvature = new SurfaceCurvature(PMPmesh);
	curvature->analyze(1);

	Scalar min = std::numeric_limits<Scalar>::max();
	Scalar max = -std::numeric_limits<Scalar>::max();

	

	switch (type)
	{
	default:
		curvature->mean_curvature_to_texture_coordinates();
		for (auto v : PMPmesh.vertices()) {
			min = std::min(min, curvature->mean_curvature(v));
			max = std::max(max, curvature->mean_curvature(v));
		}
		break;
	case(1):
		curvature->max_curvature_to_texture_coordinates();
		for (auto v : PMPmesh.vertices()) {
			min = std::min(min, curvature->min_curvature(v));
			max = std::max(max, curvature->max_curvature(v));
		}
		break;
	case(2):
		curvature->gauss_curvature_to_texture_coordinates();
		for (auto v : PMPmesh.vertices()) {
			min = std::min(min, curvature->gauss_curvature(v));
			max = std::max(max, curvature->gauss_curvature(v));
		}
		break;
	}


	//Colors
	auto texture = PMPmesh.vertex_property<TexCoord>("v:tex");
	auto colors = PMPmesh.add_vertex_property<Color>("v:color");
	std::ofstream myfile;
	myfile.open("C:/IBOIS57/_Code/Software/CPP/PMP/PMPConsole/x64/Release/PMPCurvature.txt");
	for (auto v : PMPmesh.vertices())
	{
		auto value = *texture[v].data();
		myfile << "Value " << value <<  std::endl;

		value = value < 0 ? 0 : value;
		value = value > 1 ? 1 : value;


		auto c = value < 0.5 ? interpolate(rgb{ 0.0,0,1.0 }, rgb{ 1.0,1.0,1.0 }, value) : interpolate(rgb{ 1.0,1.0,1.0 },rgb{ 1.0,0,0.0 }, value);
		colors[v] = Point((int)(c.r*255.0), (int)(c.g * 255.0), (int)(c.b * 255.0));

	}
	myfile.close();


	//Destroy curvature
	curvature->~SurfaceCurvature();

	return PMPmesh.vertex_property<TexCoord>("v:tex");

}
```

**Comment by mbotsch** [comment]
You're right that some texture coordinates might be outside the interval [0,1]. The function `SurfaceCurvature::curvature_to_texture_coordinates()` discards the smallest and largest 5% of values for computing the color scale, since otherwise extreme curvature values (mostly due to numerical issues) mess up the color coding. These 10% of values will in the end be outside of [0,1].

If you want to avoid this, you can simply compute the texture coordinates yourself, by copying `SurfaceCurvature::curvature_to_texture_coordinates()` and leaving out the outlier removal.
