### ISSUE TITLE
Remesh with Fixed Vertices and Edge

### ISSUE THREAD

**Issue by petrasvestartas** [pmp-library/pmp-library#79]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible to remesh with only edge angle feature:   

```
    SurfaceFeatures sf(PMPmesh);
    sf.detect_angle(25);
```

**Describe the solution you'd like**
Is it possible to fix specific vertex indices and edges?
For example a flat mesh with user specified points:
![image](https://user-images.githubusercontent.com/18013985/128153317-27eaba9e-1059-437f-adc0-aeea034a0a6b.png)

Currently it would just remesh like this:
![image](https://user-images.githubusercontent.com/18013985/128153566-26d09c6d-7c4f-4ea0-845f-233d544f20fa.png)

**Comment by dsieger** [comment]
You can always mark any vertices / edges as feature by hand, i.e., by setting the corresponding properties. Have a look at `SurfaceFeatures.cpp`.

**Comment by petrasvestartas** [comment]
Thank you
