### ISSUE TITLE
Inheriting from MeshViewer on Windows crashes due to the imgui context being null

### ISSUE THREAD

**Issue by bahorn** [pmp-library/pmp-library#87]
**Describe the bug**

On Windows, `mpview` (and any program importing `pmp_vis.dll`) will crash on startup after calling an Imgui command in a class that inherits from MeshViewer.

This is because the global variable storing the imgui context is not available from across DLL boundaries.

**To Reproduce**

1. Open the project in Visual Studio 2019
2. Select the mpview target
3. Compile and run
4. Encounter a crash due to a NULL dereference.

You can also confirm this being tied to the imgui context by commenting out everything in `MeshProcessingViewer::process_imgui()` after the initial `MeshViewer::process_imgui()` call, and see that it no longer crashes.

**Expected behavior**

Not crash :)

**Environment:**

 - OS: Windows 10
 - Compiler: msvc from Visual Studio 2019.
 - Build type: Debug

**Additional context**

I wrote a patch [1], that exposes the imgui context as a protected member, but it requires users to then call `ImGui::SetCurrentContext()` in the constructor of their mesh viewers. Not really sure how you would get around that however.

This is the same issue someone encountered in [2], which resulted in [3].

[1] https://gist.github.com/bahorn/4046a61778fa85a4bd57211416632182
[2] https://github.com/ocornut/imgui/issues/2292
[3] https://github.com/ocornut/imgui/commit/fcd61e0c5931500299f26afe673e12b527e5960d#diff-cee9beb740469eb5192dfe94aaee7320932590adade9d9b1d2ee392ac2e1e88cR1042

**Comment by dsieger** [comment]
Thanks for reporting, this is not so nice indeed. I I'd rather switch back to using static libraries for the visualisation module instead. Asking users to remember to add some function call in their viewer constructors seems like a recipe for failure and frustration.
