### ISSUE TITLE
Tried to open OBJ file with 1 million vertices, it crashed with segmentation fault. 

### ISSUE THREAD

**Issue by rajkr09** [pmp-library/pmp-library#88]
The Buddha.obj model has 1 million vertices. It could not open. Also i recompiled by enabling 64 bit Scalar and Index, but still it failed.

It failed at Line 103 in Properties.h file on the Assert statement.
adialmesh: /home/rajkumar/eclipse-workspace20/radialmesh/src/algorithms/../Properties.h:105: pmp::PropertyArray<T>::reference pmp::PropertyArray<T>::operator[](size_t) [with T = pmp::SurfaceMesh::VertexConnectivity; pmp::PropertyArray<T>::reference = pmp::SurfaceMesh::VertexConnectivity&; size_t = long unsigned int]: Assertion `idx < data_.size()' failed.

I tried to the print the idx and data_size. 
idx :543521
data :543522
idx :543522
data :543523
**idx :543523**
data :543524
**idx :4294423771**
data :543524

Suddenly the idx is incrementing to a higher value. Not sure what the problem is?
You can download the buddha.obj from https://casual-effects.com/g3d/data10/

**Comment by rajkr09** [comment]
Looks like obj loader is having issue beyond certain number of vertices. When i tried to add 1 million vertices directly, it got added without any issue.

**Comment by thovide** [comment]
Hello, I looked at the obj file and it contains weird vertices indexes for the faces definitions : they're negative. I don't know if it's in a way or another in obj format specification, but the PMP code doesn't support it : the negative number is put in an unsigned int, creating a huge interger... I tried to fix on my side by adding an abs call in SurfaceMeshIO.cpp: 
                            vertices.emplace_back(abs(atoi(p0)) - 1);

With this fix, you can open the file, but it's not good, it looks like the vertices of the faces are not the right ones. Those negative indexes must have a specific meaning, I'll try to dig more into this...
