### ISSUE TITLE
Mesh repair

### ISSUE THREAD

**Issue by cdcseacave** [pmp-library/pmp-library#9]
First of all thank you for sharing this great library.

I am developing an photogrammetry module ([OpenMVS](https://github.com/cdcseacave/openMVS)) and so I am using meshes at very low level. While this library would be enough for 99% of my needs, it has one feature missing, like most of the mesh libraries out there: repair a non-manifold mesh. During MVS reconstruction it is possible to get meshes with few non-manifold vertices/edges, so before doing any further processing I need to fix them (preferably not by simply deleting them, but by repairing: add a new vertex for non-manifold vertices, etc).

Is this library supporting this? I'm not able to find it. If I'd had that feature I will immediately switch OpenMVS to use it instead of VCG, which offers a lot of functionality, but has a very strange structure and many bugs.

**Comment by dsieger** [comment]
We actually thought about adding a feature like this. However, this is unlikely to arrive soon.

**Comment by mbotsch** [comment]
Let me add one question: Would it be sufficient for you to simply duplicate the non-manifold vertices? This would let to a manifold mesh, but with possibly quite some isolated faces. Hence further processing (e.g. remeshing) might not lead to the extected results. This duplication could be done quite easily.

What Daniel was mentioning is a proper representation of non-manifold situation that also allows for processing and optimization. This might take us quite some time...

**Comment by cdcseacave** [comment]
That helps, of course, but it is not ideal and also will not motivate me to invest time in replacing an imperfect mesh processing library with an other imperfect one.

**Comment by mbotsch** [comment]
Ok. Good luck finding the perfect one ;-)

**Comment by cdcseacave** [comment]
thx, will do!
