### ISSUE TITLE
Smoothing & Cotan Laplacian

### ISSUE THREAD

**Issue by thovide** [pmp-library/pmp-library#94]
Hello,

not sure if it's a request or a question!

When using cotan laplacian, the smoothing process result seems highly dependent from the mesh scale. For Implicit Smoothing for example, with a given time step, the smoothing  is very different depending if a cube mesh edge is 1mm or 100mm. 

Looking at the code, I suppose it comes from weights applied in smoothing process, that depend from voronoi_area. 

Is there a smart way to normalize this to get predictable results? I'm thinking to compute a custom time step by multiplying the initial one by square of mean edge length for example... (I will try this) Or is there a better way that you could suggest?

Anyway, thanks for the super library, still loving it (and really eager to see improvements like polygon laplacian one and new powerful algorithms integrated)

Edit : tested the above strategy and it works fine. Still interested in an answer if you have a better idea or think to integrate a kind of normalization in your algorithm

**Comment by dsieger** [comment]
Hi,

In the past, I sometimes normalized meshes to the unit cube in order to avoid problems with overly large coordinates. I guess what you just tried gives something similar. However, I don't think this is a one-size-fits-all solution, so I'd rather not bake this into the code.

**Comment by thovide** [comment]
Hi,

no I didn't normalize the mesh but the time step. Something like

//  cotan uses voronoi_area in weight computation so makes the result totally unpredictable for a given time_step

        if (!laplacian)         
       {
            double mean = 0;
            for (auto e : _TriMesh->edges())
            {
                mean += _TriMesh->edge_length(e) ;
            }
            static double factor = 10.0; // just to be able to test different values in debug mode
            mean /= _TriMesh->n_edges();
            mean *= factor;
            time_step *= mean * mean;
        }
