### ISSUE TITLE
Surface triangulation using the objective "MAX_ANGLE" generates wrong result

### ISSUE THREAD

**Issue by SabyrAltybaev** [pmp-library/pmp-library#95]
**Describe the bug**
I tried to triangulate a 3D polygon (non planar) using a "SurfaceTriangulation" class. Using the "MIN_AREA" objective the polygon was triangulated just fine. But using the "MAX_ANGLE" generated the result that I wasn't expecting. I don't know if it's expected result for non planar polygons.

**To Reproduce**
1. Launch the "mpview" project and load the "TestPoly.obj" file
[TestPoly.zip](https://github.com/pmp-library/pmp-library/files/7829018/TestPoly.zip)

2. Show the polygon lines by pressing 'H'
3. Triangulate the polygon by pressing 'T'

**Expected behavior**
I was expecting to get correctly triangulated mesh like Blender generates

**Screenshots**
Loaded polygon: 
![Pmp_before_triangulation](https://user-images.githubusercontent.com/32504577/148553174-98329a0c-6935-4830-a1b0-f2328c321cde.PNG)

The result generated by "SurfaceTriangulation":
![Pmp_tri_maxangle](https://user-images.githubusercontent.com/32504577/148551003-55adfb57-c298-47c6-b7ec-a4a234994e8d.PNG)

the result generated by Blender:
![Blender_tri](https://user-images.githubusercontent.com/32504577/148553197-1fb0ad15-02d2-4f1a-b9a5-bdda5e09c539.PNG)

**Environment (please complete the following information):**
 - OS: [Windows 10 x64]
 - Compiler: [MSVC 2019]
 - Build type: [Debug]

**Comment by dsieger** [comment]
I think this "works" as expected since the algorithm is only optimizing for the max angle and nothing else.
