### ISSUE TITLE
fill_hole does not work for an obvious hole in the mesh

### ISSUE THREAD

**Issue by licheng0794** [pmp-library/pmp-library#98]
I am using pmp to fill hole for a mesh.  pmp first detects a hole from the mesh. After hole-fill was applied, the hole is still there.

The code is below: 

pmp::SurfaceMesh mesh;
mesh.read("squirrel_sideholes.obj");
  
pmp::SurfaceHoleFilling hf(mesh);
Halfedge h = find_boundary(mesh);

if (!h.is_valid())
{
      cout << "no hole in the mesh!" << endl;
      return;
}
hf.fill_hole(h);

h = find_boundary(mesh);
if (!h.is_valid())
{
    cout << "no more hole in the mesh!" << endl;
}
else
{
    cout << "hole again in the mesh!" << endl;
}

The data is 
[squirrel_sideholes.zip](https://github.com/pmp-library/pmp-library/files/8045360/squirrel_sideholes.zip)

**Comment by dsieger** [comment]
There are two holes in the mesh. Have a look at it using the `mpview` application. Use "Hole Filling" -> "Close smallest hole" twice. Done.
