### ISSUE TITLE
pmp fails at building - on Windows with minGW

### ISSUE THREAD

**Issue by Jas-y** [pmp-library/pmp-library#99]
# Description

The build fails:

pmp-library\build>mingw32-make -f Makefile  
[  1%] Building C object CMakeFiles/glew.dir/external/glew/src/glew.c.obj  
[  2%] Linking C static library libglew.a  
[  2%] Built target glew  
[  3%] Building CXX object external/stb_image/CMakeFiles/stb_image.dir/stb_image.cpp.obj
[  4%] Building CXX object external/stb_image/CMakeFiles/stb_image.dir/stb_image_write.cpp.obj
[  5%] Linking CXX static library ..\..\libstb_image.a
[  5%] Built target stb_image
[  6%] Building C object external/glew/src/CMakeFiles/glfw.dir/context.c.obj
[  7%] Building C object external/glew/src/CMakeFiles/glfw.dir/init.c.obj
[  8%] Building C object external/glew/src/CMakeFiles/glfw.dir/input.c.obj
[  9%] Building C object external/glew/src/CMakeFiles/glfw.dir/monitor.c.obj
[ 10%] Building C object external/glew/src/CMakeFiles/glfw.dir/vulkan.c.obj
[ 11%] Building C object external/glew/src/CMakeFiles/glfw.dir/window.c.obj
[ 12%] Building C object external/glew/src/CMakeFiles/glfw.dir/win32_init.c.obj
[ 13%] Building C object external/glew/src/CMakeFiles/glfw.dir/win32_joystick.c.obj
[ 14%] Building C object external/glew/src/CMakeFiles/glfw.dir/win32_monitor.c.obj
[ 15%] Building C object external/glew/src/CMakeFiles/glfw.dir/win32_time.c.obj
[ 16%] Building C object external/glew/src/CMakeFiles/glfw.dir/win32_thread.c.obj
[ 17%] Building C object external/glew/src/CMakeFiles/glfw.dir/win32_window.c.obj
[ 18%] Building C object external/glew/src/CMakeFiles/glfw.dir/wgl_context.c.obj
[ 19%] Building C object external/glew/src/CMakeFiles/glfw.dir/egl_context.c.obj
[ 20%] Building C object external/glew/src/CMakeFiles/glfw.dir/osmesa_context.c.obj
[ 21%] Linking C static library ..\..\..\libglfw3.a
[ 21%] Built target glfw
[ 22%] Building CXX object external/imgui/CMakeFiles/imgui.dir/imgui.cpp.obj
[ 23%] Building CXX object external/imgui/CMakeFiles/imgui.dir/imgui_demo.cpp.obj
[ 24%] Building CXX object external/imgui/CMakeFiles/imgui.dir/imgui_draw.cpp.obj
[ 25%] Building CXX object external/imgui/CMakeFiles/imgui.dir/imgui_impl_glfw.cpp.obj
[ 26%] Building CXX object external/imgui/CMakeFiles/imgui.dir/imgui_impl_opengl3.cpp.obj
[ 27%] Building CXX object external/imgui/CMakeFiles/imgui.dir/imgui_widgets.cpp.obj
[ 28%] Linking CXX static library ..\..\libimgui.a
[ 28%] Built target imgui
[ 29%] Building C object external/rply/CMakeFiles/rply.dir/rply.c.obj
gcc.exe: error: /wd4700: No such file or directory
external\rply\CMakeFiles\rply.dir\build.make:75: recipe for target 'external/rply/CMakeFiles/rply.dir/rply.c.obj' failed
mingw32-make[2]: *** [external/rply/CMakeFiles/rply.dir/rply.c.obj] Error 1
CMakeFiles\Makefile2:423: recipe for target 'external/rply/CMakeFiles/rply.dir/all' failed
mingw32-make[1]: *** [external/rply/CMakeFiles/rply.dir/all] Error 2
Makefile:164: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

## How to Reproduce

1. Recursively clone the repo: git clone --recursive https://github.com/cg-tub/hrtf_mesh_grading.git
2. on Windows 10 command prompt, using minGW, build the project with no special options.

## System Info

Host Name:                 DKCPHHPC177N1X
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Original Install Date:     09/12/2021, 00:53:50
System Boot Time:          18/01/2022, 11:04:59
System Manufacturer:       LENOVO
System Model:              -
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1696 Mhz
BIOS Version:              LENOVO N22ET56W (1.33 ), 18/07/2019
Total Physical Memory:     8,026 MB
Available Physical Memory: 549 MB
Virtual Memory: Max Size:  30,170 MB
Virtual Memory: Available: 11,810 MB
Virtual Memory: In Use:    18,360 MB

## Cmake Output

pmp-library\build>cmake .. -G "MinGW Makefiles"
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Looking for dinput.h
-- Looking for dinput.h - not found
-- Looking for xinput.h
-- Looking for xinput.h - not found
-- Performing Test _GLFW_HAS_DEP
-- Performing Test _GLFW_HAS_DEP - Success
-- Performing Test _GLFW_HAS_ASLR
-- Performing Test _GLFW_HAS_ASLR - Success
-- Performing Test _GLFW_HAS_64ASLR
-- Performing Test _GLFW_HAS_64ASLR - Failed
-- Using Win32 for window creation
-- No build type specified. Using 'Release' as default.
-- clang-tidy not found.
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
-- Found OpenGL: opengl32
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) (Required is at least version "1.9.1")
-- clang-format not found.
-- Configuring done
-- Generating done
-- Build files have been written to: /pmp-library/build

**Comment by dsieger** [comment]
Hi Jason,

Thanks for your report, but I don't think this went to the right address:

1. The issue you are reporting is not against PMP, but another project using our library (https://github.com/cg-tub/hrtf_mesh_grading.git)
2. The other project is using a fork with changes, based on an _unreleased_ version of our library
3. The latest version of our library should compile with MinGW, at least someone contributed fixes some time ago. See fb43578d881e4e2ef9c24b5a3383a6ebccf2c40f
4. Note, however, that in general we do not officially support MinGW. See the [installation guide](http://www.pmp-library.org/installation.html) as well. Patches to add support are welcome, but I won't invest time on it.

Thanks,
Daniel

**Comment by Jas-y** [comment]
Hi Daniel,

Thanks for the reply.

Indeed, I was using their fork, my bad.

Consequently, I tried building the latest version of you library (still compiling with minGW), and the build gets stuck at the "google test".

Have you seen this error before? 
(minGW could be the reason of this error, in that case, I won't insist)

Thanks in advance.
/Jason

[ 75%] Building CXX object tests/CMakeFiles/googletest.dir/__/external/googletest/googletest/src/gtest-all.cc.obj
In file included from C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/include/gtest/internal/gtest-internal.h:40:0,
                 from C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/include/gtest/gtest.h:62,
                 from C:\Users\jytissieres\Desktop\pmp-library\external\googletest\googletest\src\gtest-all.cc:38:
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/include/gtest/internal/gtest-port.h: In function 'int testing::internal::posix::StrCaseCmp(const char*, const char*)':
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/include/gtest/internal/gtest-port.h:2002:25: error: '_stricmp' was not declared in this scope
   return _stricmp(s1, s2);
                         ^
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/include/gtest/internal/gtest-port.h: In function 'char* testing::internal::posix::StrDup(const char*)':
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/include/gtest/internal/gtest-port.h:2004:58: error: '_strdup' was not declared in this scope
 inline char* StrDup(const char* src) { return _strdup(src); }
                                                          ^
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/include/gtest/internal/gtest-port.h: In function 'int testing::internal::posix::FileNo(FILE*)':
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/include/gtest/internal/gtest-port.h:2012:52: error: '_fileno' was not declared in this scope
 inline int FileNo(FILE* file) { return _fileno(file); }
                                                    ^
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/include/gtest/internal/gtest-port.h: In function 'FILE* testing::internal::posix::FDOpen(int, const char*)':
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/include/gtest/internal/gtest-port.h:2090:71: error: 'fdopen' was not declared in this scope
 inline FILE* FDOpen(int fd, const char* mode) { return fdopen(fd, mode); }
                                                                       ^
In file included from C:\Users\jytissieres\Desktop\pmp-library\external\googletest\googletest\src\gtest-all.cc:41:0:
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest.cc: In static member function 'static bool testing::internal::String::CaseInsensitiveWideCStringEquals(const wchar_t*, const wchar_t*)':
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest.cc:2104:27: error: '_wcsicmp' was not declared in this scope
   return _wcsicmp(lhs, rhs) == 0;
                           ^
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest.cc: In member function 'int testing::UnitTest::Run()':
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest.cc:5411:21: error: '_OUT_TO_STDERR' was not declared in this scope
     _set_error_mode(_OUT_TO_STDERR);
                     ^~~~~~~~~~~~~~
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest.cc:5411:35: error: '_set_error_mode' was not declared in this scope
     _set_error_mode(_OUT_TO_STDERR);
                                   ^
In file included from C:\Users\jytissieres\Desktop\pmp-library\external\googletest\googletest\src\gtest-all.cc:42:0:
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest-death-test.cc: In member function 'virtual testing::internal::DeathTest::TestRole testing::internal::WindowsDeathTest::AssumeRole()':
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest-death-test.cc:772:24: error: '_MAX_PATH' was not declared in this scope
   char executable_path[_MAX_PATH + 1];  // NOLINT
                        ^~~~~~~~~
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest-death-test.cc:774:65: error: 'executable_path' was not declared in this scope
                                                                 executable_path,
                                                                 ^
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest-death-test.cc:309:38: note: in definition of macro 'GTEST_DEATH_TEST_CHECK_'
     if (!::testing::internal::IsTrue(expression)) { \
                                      ^~~~~~~~~~
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest-death-test.cc:798:11: error: 'executable_path' was not declared in this scope
           executable_path, const_cast<char*>(command_line.c_str()),
           ^
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest-death-test.cc:309:38: note: in definition of macro 'GTEST_DEATH_TEST_CHECK_'
     if (!::testing::internal::IsTrue(expression)) { \
                                      ^~~~~~~~~~
In file included from C:\Users\jytissieres\Desktop\pmp-library\external\googletest\googletest\src\gtest-all.cc:43:0:
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest-filepath.cc: In static member function 'static testing::internal::FilePath testing::internal::FilePath::GetCurrentDir()':
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest-filepath.cc:49:26: error: '_MAX_PATH' was not declared in this scope
 # define GTEST_PATH_MAX_ _MAX_PATH
                          ^
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest-filepath.cc:102:12: note: in expansion of macro 'GTEST_PATH_MAX_'
   char cwd[GTEST_PATH_MAX_ + 1] = { '\0' };
            ^~~~~~~~~~~~~~~
C:/Users/jytissieres/Desktop/pmp-library/external/googletest/googletest/src/gtest-filepath.cc:103:27: error: 'cwd' was not declared in this scope
   return FilePath(_getcwd(cwd, sizeof(cwd)) == nullptr ? "" : cwd);
                           ^~~
tests\CMakeFiles\googletest.dir\build.make:75: recipe for target 'tests/CMakeFiles/googletest.dir/__/external/googletest/googletest/src/gtest-all.cc.obj' failed
mingw32-make[2]: *** [tests/CMakeFiles/googletest.dir/__/external/googletest/googletest/src/gtest-all.cc.obj] Error 1
CMakeFiles\Makefile2:811: recipe for target 'tests/CMakeFiles/googletest.dir/all' failed
mingw32-make[1]: *** [tests/CMakeFiles/googletest.dir/all] Error 2
Makefile:164: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by dsieger** [comment]
Sorry, no idea, I never used MinGW.

However, compiling tests (and Google Test) is not required to build and use the library itself. You can disable building tests by setting the PMP_BUILD_TESTS cmake option to OFF:

```
cmake -DPMP_BUILD_TESTS=OFF
```

Hope this helps
